corda/corda-docs-portal

config.toml
themes/doks/assets/js/vendor/googleanalytics.js
themes/doks/layouts/partials/head/head.html

DOC-3121 Change to google analytics setup

DOC-3121 Change to google analytics setup

---

themes/doks/layouts/partials/head/script-header.html

DOC-3114 Added facet-based search per project/version/language

DOC-3114 Added facet-based search per project/version/language

---

content/en/platform/corda/5.0-dev-preview-1/packaging/cordapp-builder.md

https://docs.r3.com/en/platform/corda/5.0-dev-preview-1/packaging/cordapp-builder.html

DOC-3328 Corrected colour by changing html code from attention (unsupported) to note.

---

content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
content/en/platform/corda/4.8/enterprise/platform-support-matrix.md

Changing CRDB version numbers for patch release.

DOC-3585: Update CRDB version on platform support matrix / notary deployment

---

content/en/platform/corda/4.6/enterprise/network/business-network-membership.md
content/en/platform/corda/4.6/open-source/business-network-membership.md
content/en/platform/corda/4.7/enterprise/network/business-network-membership.md
content/en/platform/corda/4.7/open-source/business-network-membership.md
content/en/platform/corda/4.8/enterprise/network/business-network-membership.md
content/en/platform/corda/4.8/open-source/business-network-membership.md

Added missing repo link to 4.6, 4.7, and 4.8 in OS and ENT.

DOC-1779 [BNE] Missing repo link

---

content/en/platform/corda/4.1/enterprise/running-a-notary-cluster/notary-metrics.md
content/en/platform/corda/4.2/enterprise/running-a-notary-cluster/notary-metrics.md
content/en/platform/corda/4.3/enterprise/running-a-notary-cluster/notary-metrics.md
content/en/platform/corda/4.4/enterprise/notary/notary-metrics.md
content/en/platform/corda/4.5/enterprise/notary/notary-metrics.md
content/en/platform/corda/4.6/enterprise/notary/notary-metrics.md
content/en/platform/corda/4.7/enterprise/notary/notary-metrics.md
content/en/platform/corda/4.8/enterprise/notary/notary-metrics.md

Fixing issues with font, links, and some formatting.

DOC-83: Fix issues in highly-available notary metrics page

---

content/en/platform/corda/4.6/open-source/corda-configuration-fields.md
content/en/platform/corda/4.7/open-source/corda-configuration-fields.md
content/en/platform/corda/4.8/enterprise/node/operating/node-database-tables.md
content/en/platform/corda/4.8/open-source/corda-configuration-fields.md

On the fence about 2 things:
1. Does this need an SME review? I'm leaning towards no.
2. Use of the word please in the docs. Kind of lean towards not liking it personally.

DOC-2296: Adding `serviceLegalName` requirement to OS notary

---

content/en/platform/corda/1.0/cenm/network-map.md
content/en/platform/corda/1.1/cenm/network-map.md
content/en/platform/corda/1.2/cenm/network-map.md
content/en/platform/corda/1.3/cenm/network-map.md
content/en/platform/corda/1.4/cenm/network-map.md
content/en/platform/corda/1.5/cenm/network-map.md

Remove reference to nonexistent packageOwnership field from CENM 1.0 - 1.5

DOC-524 remove reference to packageOwnership

---

content/en/platform/corda/1.1/cenm/signing-service.md

Already fixed in later versions.

DOC-1789 Typo corrected in signing service CENM 1.1

---

content/en/platform/corda/4.8/enterprise/node/setup/corda-configuration-fields.md
content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
content/en/platform/corda/4.8/enterprise/platform-support-matrix.md

A couple of quick fixes in parts of the database setup picked up by QA. Ticket at https://r3-cev.atlassian.net/browse/DOC-3451 - note part 4 both config strings are fine.

DOC-3451: Notary Database setup docs inconsistencies

---

content/en/platform/corda/4.4/enterprise/node/component-topology.md
content/en/platform/corda/4.5/enterprise/node/component-topology.md
content/en/platform/corda/4.6/enterprise/node/component-topology.md
content/en/platform/corda/4.6/enterprise/release-notes-enterprise.md
content/en/platform/corda/4.7/enterprise/node/component-topology.md
content/en/platform/corda/4.8/enterprise/tools-config-obfuscator.md

Turning the attached list to the node deployment diagram into a numbered rather than bulleted list.

DOC-468: Node deployment diagram bulletpoints -> numbers

---

content/en/apps/bankinabox/bank-index.md

Bank in a box was deleted by mistake - adding it back in.

DOC-3712 add bank in a box back in

---

content/en/platform/corda/4.7/enterprise/node/management-console/index.md
content/en/platform/corda/4.8/enterprise/node/management-console/index.md
content/en/release-notes/_index.md

BEFORE MERGING: update alerts page.

DOC-3748 Added note about Log4j dependency to node management console.

---

content/en/platform/corda/1.5/cenm/jira-setup.md

DOC-3767 CENM Jira Setup: Jira User Privileges

---

content/en/platform/corda/4.4/enterprise/node/corda-firewall-component.md
content/en/platform/corda/4.5/enterprise/node/corda-firewall-component.md
content/en/platform/corda/4.6/enterprise/node/corda-firewall-component.md
content/en/platform/corda/4.7/enterprise/node/corda-firewall-component.md
content/en/platform/corda/4.8/enterprise/node/corda-firewall-component.md

ENT-6555 Added missing artemis keystore details to bridge config in firewall docs

---

content/en/platform/corda/4.0/open-source/docker-image.md
content/en/platform/corda/4.1/open-source/docker-image.md
content/en/platform/corda/4.3/open-source/docker-image.md
content/en/platform/corda/4.4/open-source/docker-image.md
content/en/platform/corda/4.5/open-source/docker-image.md
content/en/platform/corda/4.6/open-source/docker-image.md
content/en/platform/corda/4.7/open-source/docker-image.md
content/en/platform/corda/4.8/open-source/docker-image.md

Copied version per version, Enterprise to Open Source.

DOC-3715 Added description of how to run db migrations (copied CE to OS)

---

content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-contract-2.md
content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-contract.md
content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-state-2.md
content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-state.md

Preview site queued to build here: https://tolkien.preview.docs.r3.com/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-state.html

DOC-3852 DOC-3853: Added java samples to contracts and states tutorials.

---

content/en/platform/corda/4.8/open-source/release-notes.md

If these instructions are satisfactory, I will update release notes for OS 4.4-4.7 with the same.

DOC-3878 Added instructions on how to download latest version of OS4.8

---

content/en/platform/corda/4.8/enterprise/operations/deployment/host-prereq.md

Small bug on postgres version.

DOC-3871: Postgres version support update

---

content/en/platform/corda/4.8/enterprise/node/operating/node-database-admin.md
content/en/platform/corda/4.8/enterprise/node/setup/host-prereq.md
content/en/platform/corda/4.8/enterprise/operations/deployment/notary-deployment.md
content/en/platform/corda/4.8/enterprise/platform-support-matrix.md

Making sure version numbers are both consistent and reflect most recently supported versions

DOC-3442: Postgres and CockroachDB version number fixing

---

content/en/platform/corda/5.0-dev-preview-1/tutorials/run-demo-cordapp.md

This PR fixes a couple of small typos that caused unexpected errors when going through the solar-system tutorial.

Fix a couple of typos in the JSON flow parameters

---

assets/jsconfig.json
content/en/release-notes/_index.md
content/en/release-notes/corda-community-4.9.md
content/en/release-notes/log4j-patches.md
package-lock.json

3 small fixes in the Release Notes area

DOC-3960: corrected 3 minor errors in the Releases area

---

content/en/platform/corda/4.9/community/node-docker-deployments.md

An update to @vkolomeyko pull request [624](https://github.com/corda/corda-docs-portal/pull/624).

ENT-6490: Update Node Docker instruction for OS 4.9

---

content/en/platform/corda/4.8/enterprise/docker-image.md
content/en/platform/corda/4.8/open-source/docker-image.md
content/en/platform/corda/4.9/community/docker-image.md
content/en/platform/corda/4.9/enterprise/docker-image.md

Updating style and links to be up to date and adhere to style guide

DOC-3917: Improve docker-image.md page 

---

content/en/platform/corda/4.9/community/node-administration.md
content/en/platform/corda/4.9/enterprise/operations/deployment/running-a-node.md

See: https://r3-cev.atlassian.net/browse/DOC-3997

DOC-3997: Publishing node status in logging parameters

---

content/en/platform/corda/5.0-dev-preview-2/introduction/what-is.md

test commit

---

content/en/platform/corda/5.0-dev-preview-2/getting-started/running-your-first-cordapp/run-first-cordapp.md

Fixed typos in Running First Cordapp topic

Fixed typos in Running First Cordapp topic

---

content/en/platform/corda/5.0-dev-preview-2/getting-started/cordapp-standard-development-environment/csde.md

folder for test source was wrong (pointing to main instead of test folder).

Fix in docs (typo)

---

content/en/platform/_index.md
content/en/platform/corda/4.9/enterprise/_index.md
content/en/platform/corda/4.9/enterprise/app-upgrade-notes-enterprise.md
content/en/platform/corda/4.9/enterprise/node/operating/monitoring-and-logging/overview.md
content/en/platform/corda/_index.md

1. Multiple instances of OS > CE
2. Both indexes updated to include 4.9 CE and E
3. Both indexes link formats updated to look better

Doc 4172 version links added

---

content/en/platform/corda/4.9/community/api-flows.md

Fixed typo

---

content/en/platform/corda/4.9/enterprise/cordapps/api-testing.md

Fixed link to integration tutorial for 4.9.

DOC-4305 - Fixed link to tutorial

---

content/en/platform/corda/4.9/enterprise/node-upgrade-notes.md
content/en/platform/corda/4.9/enterprise/release-notes-enterprise.md

Fixes to 4.9 upgrade procedure docs based on feedback from SBI via @yangbor3

Doc 4234 - Fixes to 4.9 upgrade procedure docs

---

content/en/platform/corda/5.0-beta/getting-started/prerequisites/prerequisites.md

Note added that in CSDE docs ports 5432, 7000,8888 should be reserved.

Doc 4371: Update CSDE docs to state the ports 5432, 7000,8888 should be reserved

---

content/en/platform/corda/5.0-dev-preview-2/getting-started/prerequisites/prerequisites.md

Section added listing required CSDE ports for DP2.

Doc 4369: Section added listing required CSDE ports

---

content/en/api-ref/_index.md

Description omitted Enterprise 4.9

Added missing v4.9

---

content/en/api-ref/_index.md
themes/doks/static/icons/no.svg
themes/doks/static/icons/yes.svg

Set both the Yes and No feedback icons to the same combination of greys.

Doc 3335 - Reduce visual prominence of feedback buttons

---

content/en/platform/corda/4.0/enterprise/api-persistence.md
content/en/platform/corda/4.0/open-source/api-persistence.md
content/en/platform/corda/4.1/enterprise/api-persistence.md
content/en/platform/corda/4.1/open-source/api-persistence.md
content/en/platform/corda/4.2/enterprise/api-persistence.md
content/en/platform/corda/4.3/enterprise/api-persistence.md
content/en/platform/corda/4.3/open-source/api-persistence.md
content/en/platform/corda/4.4/enterprise/cordapps/state-persistence.md
content/en/platform/corda/4.4/open-source/api-persistence.md
content/en/platform/corda/4.5/enterprise/cordapps/state-persistence.md
content/en/platform/corda/4.5/open-source/api-persistence.md
content/en/platform/corda/4.6/enterprise/cordapps/state-persistence.md
content/en/platform/corda/4.6/open-source/api-persistence.md
content/en/platform/corda/4.7/enterprise/cordapps/state-persistence.md
content/en/platform/corda/4.7/open-source/api-persistence.md
content/en/platform/corda/4.8/enterprise/cordapps/state-persistence.md
content/en/platform/corda/4.8/open-source/api-persistence.md
content/en/platform/corda/4.9/community/api-persistence.md
content/en/platform/corda/4.9/enterprise/cordapps/state-persistence.md

See:
https://github.com/corda/corda/issues/5254#issuecomment-794497804

DOC-1812  - replaced existing 'Persisting Hierarchical Data' section with suggested working example at GitHub link in ticket

---

content/en/platform/corda/5.0-beta/deploying/network-types.md

add links from overview steps to tutorials (Beta - was previously only done for alpha content)

add links to tutorials (Beta)

---

content/en/platform/corda/5.0-alpha/deploying/group-policy.md
content/en/platform/corda/5.0-alpha/deploying/network-types.md

* broken link reported by @williamvigorr3 
* network type page not displayed on left-hand menu

Fix reported broken link and resolve menu display issue

---

content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/onboarding/dynamic-onboarding.md

DOC-4428: Added registration context for a member as a notary service representative

added registration context for notary service representative

---

content/en/platform/corda/5.0-beta/introduction/introduction.md

update in line with the changes requested in https://github.com/corda/corda-docs-portal/pull/810

Update beta program note in line with updates on Release Notes page

---

content/en/platform/corda/5.0-beta/introduction/corda4-differences.md

Add overview of Notary differences from C4

add notary differences overview

---

content/en/platform/corda/5.0-beta/getting-started/get-started.md

CSDE will not be ready for Jan 10th release. It was agreed that rather than pulling the docs, we should add a note.

add note about csde

---

content/en/platform/corda/5.0-beta/release-notes/release-notes-c5.md

added Known Limitations

---

content/en/platform/corda/4.10/community/cordapp-build-systems.md
content/en/platform/corda/4.10/enterprise/app-upgrade-notes-enterprise.md
content/en/platform/corda/4.10/enterprise/app-upgrade-notes.md
content/en/platform/corda/4.10/enterprise/cordapps/cordapp-build-systems.md

https://r3-cev.atlassian.net/browse/DOC-4254
Updated Quasar version to 0.7.15_r3

DOC-4254 - updated Quasar version to 0.7.15_r3

---

content/en/platform/corda/5.0-beta/developing/notaries/csde.md
content/en/platform/corda/5.0-beta/developing/notaries/network-member-roles.md
content/en/platform/corda/5.0-beta/developing/notaries/overview.md
content/en/platform/corda/5.0-beta/developing/notaries/plugin-cordapps-notary.md

Preview here https://amie.preview.docs.r3.com/en/platform/corda/5.0-beta/developing/notaries/overview.html

DOC-4513: Updated identifier in notary doc to solve Hugo warning

---

content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/deploy-corda-cluster.md
content/en/platform/corda/5.0-beta/developing/getting-started/reset-csde.md

* fix 2 links to REST API
* fix typo in reset CSDE

fix 2 links and typo

---

content/en/platform/corda/5.0-beta/release-notes/release-checksums-c5.md

Checksums were displaying on the same line

correct spacing

---

content/en/platform/corda/4.10/community/release-platform-support-matrix.md

Updated JDK versions for Community

ENT-7014 - updated JDK versions for Community 4.10

---

content/en/release-notes/eol.md

Added end of life schedule for 4.10 Enterprise and Community

DOC-4208 - added end of life schedule for 4.10 Enterprise and Community

---

content/en/platform/corda/4.10/community/release-notes.md
content/en/platform/corda/4.10/enterprise/release-notes-enterprise.md

…sed on Chris' comment. Also some typos.

Ent 8776 - Updated "Improved cryptoservice exception behavior entry" based on Chris' comment. Also some typos.

---

content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/mgm-onboarding.md

Added info about corda.group.key.session.policy and corrected inconsistency following feedback from QA

DOC-4526: corda.group.key.session.policy

---

content/en/platform/corda/4.10/community/release-notes.md
content/en/platform/corda/4.10/enterprise/release-notes-enterprise.md

Added links from release notes to OpenTelemetry topics

---

content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/dynamic-onboarding.md

correction based on QA feedback

improve code snippets

---

themes/doks/layouts/partials/head/script-header.html

update search filter on homepage

---

themes/doks/layouts/partials/head/script-header.html

Test to change Algolia filter on main homepage. Currently pages without a version are not returned. For example, "ledgergraph" in the tools area.

initial test - project OR version

---

content/en/platform/corda/4.10/enterprise/serialization-default-evolution.md
content/en/platform/corda/4.5/enterprise/serialization-default-evolution.md
content/en/platform/corda/4.6/enterprise/serialization-default-evolution.md
content/en/platform/corda/4.7/enterprise/serialization-default-evolution.md
content/en/platform/corda/4.8/enterprise/serialization-default-evolution.md
content/en/platform/corda/4.9/enterprise/serialization-default-evolution.md

Added to summary and added a note regarding contractor properties. Amos recommended that it be added to this section to say explicitly what is not supported after the section mentioning what is supported.

Niamh25 doc 1854 update summary for default class evolution

---

content/en/platform/corda/5.0-beta/developing/getting-started/configure-the-network-participants/network-participants.md
content/en/platform/corda/5.0-beta/developing/getting-started/cordapp-standard-development-environment/csde.md
content/en/platform/corda/5.0-beta/developing/getting-started/fast-feedback-with-the-simulator/fast-feedback-with-the-simulator.md
content/en/platform/corda/5.0-beta/developing/getting-started/first-flow/code-java.md
content/en/platform/corda/5.0-beta/developing/getting-started/first-flow/code-kotlin.md
content/en/platform/corda/5.0-beta/developing/getting-started/installing-corda-cli.md
content/en/platform/corda/5.0-beta/developing/getting-started/reset-csde.md
content/en/platform/corda/5.0-beta/developing/getting-started/running-your-first-cordapp/run-first-cordapp.md
package-lock.json

Updating the getting started docs for beta 1.1

Mattb/beta 1.1 updates

---

content/en/platform/corda/4.10/enterprise/node/setup/host-prereq.md
content/en/platform/corda/4.8/enterprise/node/setup/host-prereq.md
content/en/platform/corda/4.9/enterprise/node/setup/host-prereq.md

Note specifying only the stated third parties are supported

Niamh25 doc 2893 note specifying only the stated third parties are supported

---

content/en/platform/corda/5.0-beta/corda-cli-reference/cli-commands/database.md
content/en/platform/corda/5.0-beta/corda-cli-reference/cli-commands/initial-config.md
content/en/platform/corda/5.0-beta/corda-cli-reference/cli-commands/package.md
content/en/platform/corda/5.0-beta/corda-cli-reference/cli-commands/topic.md
content/en/platform/corda/5.0-beta/corda-cli-reference/overview.md
content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/manual.md
content/en/platform/corda/5.0-beta/developing/getting-started/reset-csde.md

* changes for kebab case updates
* cross-ref added to installation

kebab case

---

content/en/archived-docs/CENM/1.0/release-notes.md
content/en/archived-docs/CENM/1.1/_index.md
content/en/platform/corda/1.2/cenm/_index.md
content/en/platform/corda/1.2/cenm/release-notes.md
content/en/platform/corda/1.2/cenm/upgrade-notes.md
content/en/platform/corda/1.3/cenm/_index.md
content/en/platform/corda/1.3/cenm/updating-network-parameters.md
content/en/platform/corda/1.4/cenm/_index.md
content/en/platform/corda/1.4/cenm/updating-network-parameters.md
content/en/platform/corda/1.5/cenm/release-notes.md
content/en/platform/corda/1.5/cenm/updating-network-parameters.md
content/en/platform/corda/1.5/cenm/upgrade-notes.md
content/en/platform/corda/4.7/enterprise/get-started/tutorials/supplementary-tutorials/tutorial-observer-nodes.md

Broken links from the first batch have been updated.

<Niamh25-DOC-4759-Brokenlinksfixed>: updated broken links first batch

---

config/_default/menus/menus.en.toml
content/en/platform/corda/5.0-beta/_index.md
content/en/platform/corda/5.0-beta/deploying/network-types.md
content/en/platform/corda/5.0-beta/operating/mutual-tls.md
content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/dynamic-onboarding.md
content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/mgm-onboarding.md
content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/mutual-tls.md
content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/session-certificates.md

Preview currently available here: https://nadine.preview.docs.r3.com/en/platform/corda/5.0-beta/operating/mutual-tls.html

add mutual TLS info and a couple of minor edits

---

content/en/platform/corda/4.10/community/get-started/get-started-landing.md
content/en/platform/corda/4.10/enterprise/apps/bankinabox/api-guide.md
content/en/platform/corda/4.10/enterprise/cordapps/cordapp-constraint-migration.md
content/en/platform/corda/4.7/enterprise/apps/bankinabox/api-guide.md
content/en/platform/corda/4.8/enterprise/apps/bankinabox/api-guide.md
content/en/platform/corda/4.8/enterprise/cordapps/cordapp-constraint-migration.md
content/en/platform/corda/4.9/enterprise/apps/bankinabox/api-guide.md

Reverts corda/corda-docs-portal#1130

Revert "Niamh25 doc 4833 broken linksfixed"

---

content/en/platform/corda/4.10/community/get-started/get-started-landing.md
content/en/platform/corda/4.10/enterprise/apps/bankinabox/api-guide.md
content/en/platform/corda/4.7/enterprise/apps/bankinabox/api-guide.md
content/en/platform/corda/4.8/enterprise/apps/bankinabox/api-guide.md
content/en/platform/corda/4.9/enterprise/apps/bankinabox/api-guide.md

Bankinabox link updated to link to the section and not the page.

Niamh25 bankinabox url doc 4851 issuewithrelativelink

---

content/en/platform/corda/4.10/community/apps/bankinabox/api-guide.md
content/en/platform/corda/4.10/community/get-started/get-started-landing.md
content/en/platform/corda/4.10/enterprise/get-started/getting-started-with-corda-4.md
content/en/platform/corda/4.7/enterprise/get-started/getting-started-with-corda-4.md
content/en/platform/corda/4.8/enterprise/get-started/getting-started-with-corda-4.md
content/en/platform/corda/4.9/enterprise/get-started/getting-started-with-corda-4.md

Broken link on community bank in box and api ref fixed

Niamh25-DOC-4861-Communitybrokenlinkfix

---

content/en/platform/corda/4.10/community/introduction/assetissuer.md
content/en/platform/corda/4.10/community/introduction/bno.md
content/en/platform/corda/4.10/community/introduction/cordanodeadmin.md
content/en/platform/corda/4.10/community/introduction/networkparticipant.md

As per title. Expanding regex to multiple files in one go.

hugo-links-one-section

---

content/en/platform/corda/4.10/enterprise/notary/installing-jpa.md
content/en/platform/corda/4.7/enterprise/notary/installing-jpa.md
content/en/platform/corda/4.9/enterprise/notary/installing-jpa.md

Updated JPA note to all applicable versions.

Niamh25-DOC-4922-JPAversions: Updated all versions with JPA note

---

content/en/platform/corda/4.10/community/api-persistence.md
content/en/platform/corda/4.10/enterprise/cordapps/state-persistence.md

Implemented same update in 4.10, previously done to 4.9 and previous:
https://github.com/corda/corda-docs-portal/pull/786 
https://r3-cev.atlassian.net/browse/DOC-1812

DOC-4924 - updated with Persisting Hierarchical Data

---

content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/manual.md

Fix indentation to resolve formatting error (https://nadine.preview.docs.r3.com/en/platform/corda/5.0-beta/deploying/deployment-tutorials/manual.html#database)

indentation error

---

content/en/platform/corda/5.0-beta/deploying/prerequisites.md

EKS only supported on EC2

---

content/en/platform/corda/5.0-beta/operating/configuration/cryptoLibrary.md
content/en/platform/corda/5.0-beta/operating/configuration/db.md
content/en/platform/corda/5.0-beta/operating/configuration/ledger-utxo.md
content/en/platform/corda/5.0-beta/operating/configuration/p2p-gateway.md
content/en/platform/corda/5.0-beta/operating/configuration/reconciliation.md
content/en/platform/corda/5.0-beta/operating/configuration/rest.md
content/en/platform/corda/5.0-beta/operating/configuration/sandbox.md
content/en/platform/corda/5.0-beta/operating/configuration/secrets.md
content/en/platform/corda/5.0-beta/operating/configuration/security.md

(Membership and Link Gateway schemas seem to use additional conditions and nesting which the current Hugo template does not support. These will follow in a future PR.)

Add config pages

---

content/en/platform/corda/5.0-beta/operating/configuration/membership.md
layouts/partials/defs-field-desc-ref-docs.html
layouts/partials/field-desc-ref-docs.html
layouts/shortcodes/generate-ref-docs.html

Preview here: https://nadine.preview.docs.r3.com/en/platform/corda/5.0-beta/operating/configuration/membership.html

add membership config page and update templates accordingly

---

content/en/platform/corda/1.5/cenm/release-notes.md

Preview built here https://amie.preview.docs.r3.com/en/platform/corda/1.5/cenm/release-notes.html

Updated CENM 1.5.7 release notes

---

content/en/platform/corda/5.0-beta/glossaryitems.json
content/en/platform/corda/5.0-beta/introduction/glossary.md
themes/doks/assets/scss/common/_global.scss
themes/doks/layouts/shortcodes/definition.html
themes/doks/layouts/shortcodes/glossary.html
themes/doks/layouts/shortcodes/tooltip.html

Test page to review the functions in action - https://nadine.preview.docs.r3.com/en/platform/corda/5.0-beta/introduction/glossary.html
(The content labelled "TEST" at the end of the page is only temporary to help to review the PR. These tooltips would actually appear throughout the Corda 5 content on any page. I've only added a few items to the glossary list, for testing purposes. This list will need to be fleshed out over the coming weeks.)

Corda 5 Glossary Functions and Styling

---

themes/doks/assets/scss/common/_global.scss
themes/doks/layouts/_default/_markup/render-heading.html

This reverts commit ba6186936c9cb593d05b1145c764ac464b25b8fd.

Revert "fixed h1 issue. (#1300)"

---

content/en/archived-docs/corda-enterprise/4.6/enterprise/secrets.md
content/en/archived-docs/corda-os/4.7/reissuing-states.md
content/en/archived-docs/corda-os/4.8/reissuing-states.md
content/en/platform/corda/1.5/cenm/cenm-console.md
content/en/platform/corda/4.10/community/reissuing-states.md
content/en/platform/corda/4.10/enterprise/cordapps/reissuing-states.md
content/en/platform/corda/4.10/enterprise/node/management-console/index.md
content/en/platform/corda/4.10/enterprise/secrets.md
content/en/platform/corda/4.7/enterprise/cordapps/reissuing-states.md
content/en/platform/corda/4.7/enterprise/node/management-console/index.md
content/en/platform/corda/4.7/enterprise/secrets.md
content/en/platform/corda/4.8/enterprise/cordapps/reissuing-states.md
content/en/platform/corda/4.8/enterprise/node/management-console/index.md
content/en/platform/corda/4.8/enterprise/secrets.md
content/en/platform/corda/4.9/community/reissuing-states.md
content/en/platform/corda/4.9/enterprise/cordapps/reissuing-states.md
content/en/platform/corda/4.9/enterprise/node/management-console/index.md
content/en/platform/corda/4.9/enterprise/secrets.md

Fixed all images that were using {{% figure with {{< figure.

Paulmoloneyr3/doc 5294/missing images

---

content/en/platform/corda/5.0/reference/corda-cli/database.md
content/en/platform/corda/5.0/reference/corda-cli/initial-config.md
content/en/platform/corda/5.0/reference/corda-cli/mgm.md
content/en/platform/corda/5.0/reference/corda-cli/package.md
content/en/platform/corda/5.0/reference/corda-cli/topic.md

Preview built here: https://amie.preview.docs.r3.com/en/platform/corda/5.0/reference/corda-cli.html

Update tabs to Bash and PowerShell

---

content/en/platform/corda/5.0/application-networks/creating/members/cpi.md
content/en/platform/corda/5.0/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/members/register.md
content/en/platform/corda/5.0/application-networks/creating/mgm/cpi.md
content/en/platform/corda/5.0/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/mgm/register.md
content/en/platform/corda/5.0/application-networks/creating/notaries.md
content/en/platform/corda/5.0/application-networks/plan.md

See preview here: https://anna.preview.docs.r3.com/en/platform/corda/5.0/application-networks.html

Add Planning content, clarify packaging steps, and link tidy up

---

content/en/platform/corda/5.0-beta/deploying/notaries/notary-deployment.md
content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/dynamic-onboarding.md

Preview built here: https://amie.preview.docs.r3.com/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/dynamic-onboarding.html#build-registration-context and https://amie.preview.docs.r3.com/en/platform/corda/5.0-beta/deploying/notaries/notary-deployment.html

Update notary registration info

---

content/en/platform/corda/5.0/developing-applications/getting-started/cordapp-standard-development-environment/csde.md

DOC-5324 - small changes

---

content/en/platform/corda/5.0-beta/operating/operating-tutorials/onboarding/static-onboarding.md

Reverts corda/corda-docs-portal#1350

Revert "test enterprise logo"

---

content/en/platform/corda/5.0/developing-applications/getting-started/cordapp-standard-development-environment/csde.md

DOC-5362 - wrapped angle brackets in code brackets

---

content/en/platform/corda/5.0/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/members/register.md
content/en/platform/corda/5.0/application-networks/creating/mgm/group-policy.md
content/en/platform/corda/5.0/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/mgm/register.md
content/en/platform/corda/5.0/application-networks/creating/mgm/virtual-node.md
content/en/platform/corda/5.0/application-networks/creating/notaries.md
content/en/platform/corda/5.0/application-networks/creating/optional/mutual-tls-connections.md
content/en/platform/corda/5.0/application-networks/creating/optional/session-certificates.md
content/en/platform/corda/5.0/application-networks/managing/member-suspension/_index.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/configuring-manual-approval-rules.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/pre-auth/configuring-pre-auth-rules.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/pre-auth/preauthenticating-tokens.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/reviewing-registration-requests.md

- `curl -u.....` should be `curl --insecure -u...`
- `Invoke-RestMethod -Headers` should be `Invoke-RestMethod -SkipCertificateCheck  -Headers`

add --insecure, etc

---

content/en/platform/corda/5.0/developing-applications/network-types/_index.md

Preview built here https://amie.preview.docs.r3.com/en/platform/corda/5.0/developing-applications/network-types.html

DOC-5163: Add network types content

---

content/en/platform/corda/5.0/developing-applications/upgrading/_index.md

Material from https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4459724853/Evolving+a+CorDapp - only material applicable to Corda 5.0 and not to any subsequent versions.

DOC-5285 - added topic on upgrading CorDapps

---

content/en/platform/corda/5.0/deploying-operating/config-users/_index.md
content/en/platform/corda/5.0/deploying-operating/config-users/managing-roles.md
content/en/platform/corda/5.0/deploying-operating/config/database-connection.md
content/en/platform/corda/5.0/deploying-operating/config/secrets.md
content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
content/en/platform/corda/5.0/deploying-operating/deployment/deploying/manual-bootstrapping.md
content/en/platform/corda/5.0/deploying-operating/deployment/prerequisites.md
content/en/platform/corda/5.0/deploying-operating/tooling/_index.md
content/en/platform/corda/5.0/reference/corda-cli/database.md
content/en/platform/corda/5.0/reference/corda-cli/initial-config.md
content/en/platform/corda/5.0/reference/corda-cli/topic.md

add links, minor edits, file rename

Link between Config Users and Manual Bootstrapping

---

content/en/platform/corda/4.10/community/get-started/get-started-landing.md
content/en/platform/corda/4.10/community/key-concepts-vault.md

Preview built here: https://amie.preview.docs.r3.com/en/platform/corda/4.10/community/get-started/get-started-landing.html

DOC-5450: Updated getting started page in community 4.10

---

content/en/platform/corda/5.0/application-networks/creating/members/cpi.md
content/en/platform/corda/5.0/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/members/register.md
content/en/platform/corda/5.0/application-networks/creating/members/virtual-node.md
content/en/platform/corda/5.0/application-networks/creating/mgm/cpi.md
content/en/platform/corda/5.0/application-networks/creating/mgm/group-policy.md
content/en/platform/corda/5.0/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/mgm/register.md
content/en/platform/corda/5.0/application-networks/creating/mgm/virtual-node.md
content/en/platform/corda/5.0/application-networks/creating/notaries.md
content/en/platform/corda/5.0/application-networks/creating/optional/mutual-tls-connections.md
content/en/platform/corda/5.0/application-networks/creating/optional/session-certificates.md
content/en/platform/corda/5.0/application-networks/managing/member-suspension/_index.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/configuring-manual-approval-rules.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/pre-auth/configuring-pre-auth-rules.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/pre-auth/preauthenticating-tokens.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/reviewing-registration-requests.md
content/en/platform/corda/5.0/deploying-operating/config/dynamic.md
content/en/platform/corda/5.0/developing-applications/packaging/code-signing/custom-cert.md
content/en/platform/corda/5.0/reference/rest-api/accessing.md

Deleted original PR for this. There were already conflicts, but with the merge of c5 branch to main, it was easier to redo the PR from scratch.

replace --insecure with -k

---

content/en/platform/corda/5.0/introduction/release-notes/5.0.0.md

release notes update for beta4

---

content/en/platform/corda/5.0/introduction/release-notes/5.0.0.md

delete dash from version

---

content/en/platform/corda/5.0/deploying-operating/vnodes/_index.md
content/en/platform/corda/5.0/deploying-operating/vnodes/x500.md

More content to follow but existing content should be a sub-page

remove placeholder content

---

content/en/platform/corda/5.0/_index.md

add alias to redirect old Beta URL that Google is returning in results

add alias 

---

content/en/platform/corda/5.0/application-networks/creating/members/virtual-node.md
content/en/platform/corda/5.0/developing-applications/api/application/persistence.md

* Some small tweaks to update the wording to reflect the rest of the doc changes since DP2
* Broken link in content/en/platform/corda/5.0/application-networks/creating/members/virtual-node.md

net corda v 5 application persistence

---

content/en/platform/corda/5.0/introduction/about-the-docs/_index.md
content/en/platform/corda/5.0/introduction/release-notes/5.0.0.md
content/en/platform/corda/eol-schedule.md

1. Fixed small issue in previous PR (release notes).
2. Uncommented EOL content, previously hidden in Beta versions.
3. Updated EOL content to include dates for GA.

Colin.hillis/doc 5503/reintroduce eol for c5 ga

---

content/en/platform/corda/5.0/glossaryitems.json
themes/doks/layouts/shortcodes/definition.html

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.0/introduction/glossary.html

Migrate glossary terms from Wiki

---

content/en/platform/corda/5.0/introduction/release-notes/legal-info/CSDE-cordapp-template-java.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/CSDE-cordapp-template-kotlin.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/corda-api.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/corda-cli.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/corda-gradle-plugins.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/corda-runtime-os.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/corda-utxo-ledger-extensions.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/corda5-enterprise.html
content/en/platform/corda/5.0/introduction/release-notes/legal-info/csde-gradle-plugin.html

Process-related internal information [here](https://r3-cev.atlassian.net/wiki/spaces/TW/pages/4401332261/Generating+a+Snyk+License+Report#Correcting-Badly-Formatted-HTML).

correct badly formatted HTML in TPN reports

---

content/en/api-ref/_index.md

..also corrected case of titles

Fix broken link to C5 API

---

content/en/platform/corda/5.0/application-networks/managing/registration-requests/configuring-manual-approval-rules.md
content/en/platform/corda/5.0/application-networks/managing/registration-requests/pre-auth/configuring-pre-auth-rules.md

Two notes added to manual member approval and pre-auth approval

Niamh25/doc 5636/note added to manual member approval

---

content/en/platform/corda/5.0/key-concepts/cordapp-dev/building/_index.md
content/en/platform/corda/5.0/key-concepts/cordapp-dev/ecosystem/_index.md

See https://github.com/corda/corda-docs-portal/pull/1589

CorDap Dev Key Concepts: Comments on previous closed PR

---

content/en/platform/corda/4.11/enterprise/cordapps/tutorial-cordapp.md

Preview built here: https://amie.preview.docs.r3.com/en/platform/corda/4.11/enterprise/cordapps/tutorial-cordapp.html#step-3-deploy-the-cordapp-locally

Added updates to 4.11 Run a sample CorDapp

---

content/en/platform/corda/5.0/application-networks/creating/members/config-node.md
content/en/platform/corda/5.0/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/members/virtual-node.md
content/en/platform/corda/5.0/application-networks/creating/mgm/config-node.md
content/en/platform/corda/5.0/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/mgm/virtual-node.md

Give two topics unique titles - might help in search results and even (as happened me) thinking it was a copy error.

DOC-5698 - unique titles

---

content/en/platform/corda/5.0/application-networks/creating/optional/_index.md

DOC-5697- Missing H1 Title

---

content/en/platform/corda/4.11/community/release-notes.md
content/en/platform/corda/4.11/enterprise/release-notes-enterprise.md

First tranche of release note updates for 4.11 Ent and Community

DOC-4655 - Release notes update

---

content/en/platform/corda/5.0/developing-applications/api/api-serialisation.md

DOC-5713 - Fix shortcode formatting 

---

content/en/platform/corda/4.10/community/building-against-non-release.md
content/en/platform/corda/4.10/community/cordapp-build-systems.md
content/en/platform/corda/4.10/community/testing.md
content/en/platform/corda/4.10/community/tutorial-cordapp.md
content/en/platform/corda/4.10/enterprise/building-against-non-release.md
content/en/platform/corda/4.10/enterprise/cordapps/cordapp-build-systems.md
content/en/platform/corda/4.10/enterprise/testing.md
content/en/platform/corda/4.7/enterprise/building-against-non-release.md
content/en/platform/corda/4.7/enterprise/cordapps/cordapp-build-systems.md
content/en/platform/corda/4.8/enterprise/building-against-non-release.md
content/en/platform/corda/4.8/enterprise/cordapps/cordapp-build-systems.md
content/en/platform/corda/4.8/enterprise/testing.md
content/en/platform/corda/4.9/community/building-against-non-release.md
content/en/platform/corda/4.9/community/cordapp-build-systems.md
content/en/platform/corda/4.9/community/testing.md
content/en/platform/corda/4.9/community/tutorial-cordapp.md
content/en/platform/corda/4.9/enterprise/building-against-non-release.md
content/en/platform/corda/4.9/enterprise/cordapps/cordapp-build-systems.md
content/en/platform/corda/4.9/enterprise/testing.md

Preview built here: https://amie.preview.docs.r3.com/

DOC-5705: Updated OSX to macOS

---

content/en/platform/corda/4.11/community/building-against-non-release.md
content/en/platform/corda/4.11/community/cordapp-build-systems.md
content/en/platform/corda/4.11/community/testing.md
content/en/platform/corda/4.11/community/tutorial-cordapp.md
content/en/platform/corda/4.11/enterprise/building-against-non-release.md
content/en/platform/corda/4.11/enterprise/cordapps/cordapp-build-systems.md
content/en/platform/corda/4.11/enterprise/testing.md

Preview built here https://amie.preview.docs.r3.com/

DOC-5715: Updated Mac OSX to macOS in 4.11

---

content/en/platform/corda/4.10/enterprise/node/operating/shell.md

DOC-5752 - fixed broken links

---

themes/doks/layouts/_default/_markup/render-heading.html
themes/doks/layouts/_default/list.html
themes/doks/layouts/_default/single.html

Rename Corda 5 version variable

---

content/en/platform/corda/5.0/release-notes/legal-info/CSDE-cordapp-template-java.html
content/en/platform/corda/5.0/release-notes/legal-info/CSDE-cordapp-template-kotlin.html
content/en/platform/corda/5.0/release-notes/legal-info/corda-api.html
content/en/platform/corda/5.0/release-notes/legal-info/corda-cli.html
content/en/platform/corda/5.0/release-notes/legal-info/corda-gradle-plugins.html
content/en/platform/corda/5.0/release-notes/legal-info/corda-runtime-os.html
content/en/platform/corda/5.0/release-notes/legal-info/csde-gradle-plugin.html

TPN reports for C5-GA have been updated with the missing copyright information

updated 5.0 TPN

---

content/en/platform/corda/4.11/enterprise/finality-flow-recovery.md

Minor fix to incorrect command syntax.

DOC-5371 - two phase finality documentation (minor fix).

---

content/en/platform/corda/4.11/community/tutorial-cordapp.md
content/en/platform/corda/4.11/enterprise/cordapps/tutorial-cordapp.md

Preview built here: https://amie.preview.docs.r3.com/en/platform/corda/4.11/enterprise/cordapps/tutorial-cordapp.html

DOC-5827: Removed duplicate Appendix B section and updated links in 4.11

---

themes/doks/layouts/partials/main/docs-navigation.html

Preview here: https://nadine.preview.docs.r3.com/

The footer nav div should not be displayed unless there is nav to display

---

content/en/platform/corda/5.0/deploying-operating/deployment/prerequisites.md
content/en/platform/corda/5.0/release-notes/support.md
themes/doks/assets/snippets/corda-5.0/prereqs-container.md
themes/doks/assets/snippets/corda-5.0/prereqs-databases.md
themes/doks/assets/snippets/corda-5.0/prereqs-messaging.md
themes/doks/assets/snippets/corda-5.0/prereqs-vault.md
themes/doks/layouts/shortcodes/snippet.html

(also fixed the comments for Snippet shortcode)
Preview here: https://colin.preview.docs.r3.com/

Add snippets for Prequisite content

---

themes/doks/assets/scss/layouts/_footer.scss
themes/doks/layouts/partials/footer/footer.html
themes/doks/layouts/partials/header/header.html

- Remove several links in the footer. These are either unnecessary or duplicated in one of the headers.
- Change R3 logo in header to link to r3.com
- Decrease footer height
Preview: https://neil.preview.docs.r3.com/

Improve Footer

---

content/en/platform/corda/5.0/developing-applications/getting-started/_index.md
content/en/platform/corda/5.0/developing-applications/getting-started/configure-the-network-participants/_index.md
content/en/platform/corda/5.0/developing-applications/getting-started/debugging-against-local-corda/_index.md
content/en/platform/corda/5.0/developing-applications/getting-started/first-flow/code-java.md
content/en/platform/corda/5.0/developing-applications/getting-started/first-flow/code-kotlin.md
content/en/platform/corda/5.0/developing-applications/getting-started/installing/_index.md
content/en/platform/corda/5.0/developing-applications/getting-started/overview/_index.md
content/en/platform/corda/5.0/developing-applications/getting-started/running-your-first-cordapp/_index.md
content/en/platform/corda/5.0/developing-applications/getting-started/utxo-ledger-example-cordapp/cordapp-chat/_index.md
content/en/platform/corda/5.0/developing-applications/getting-started/utxo-ledger-example-cordapp/running-the-chat-cordapp/_index.md

Including:
- Move further up in the Developing section
- Add mini-tocs at start of topics
- Reduce size of images, where applicable
- Remove tooltips from notes
- Update code formatting in table
- Correct spacing
Preview here: https://neil.preview.docs.r3.com/en/platform/corda/5.0/developing-applications/getting-started.html

General CSDE Updates

---

themes/doks/layouts/index.html

Updates to homepage: add links to Corda 4/Corda 5 tools, remove old card

---

content/en/platform/corda/5.0/deploying-operating/config/_index.md
content/en/platform/corda/5.0/deploying-operating/config/dynamic.md
content/en/platform/corda/5.1/application-networks/managing/_index.md
content/en/platform/corda/5.1/application-networks/managing/endpoints/_index.md
content/en/platform/corda/5.1/deploying-operating/config/dynamic.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/application-networks/managing/endpoints.html
Will need links to new topic created for https://r3-cev.atlassian.net/browse/DOC-4363

Endpoint change

---

content/en/api-ref/api-ref-corda-4.md

Preview built here: https://amie.preview.docs.r3.com/en/api-ref/api-ref-corda-4.html

DOC-5845: Remove random text from Corda 4 API ref 

---

content/en/platform/corda/5.1/application-networks/creating/members/cpi.md
content/en/platform/corda/5.1/application-networks/creating/members/virtual-node.md
content/en/platform/corda/5.1/application-networks/creating/mgm/cpi.md
content/en/platform/corda/5.1/application-networks/creating/mgm/register.md
content/en/platform/corda/5.1/application-networks/creating/mgm/virtual-node.md
content/en/platform/corda/5.1/deploying-operating/config/dynamic.md
content/en/platform/corda/5.1/deploying-operating/vnodes/retrieving.md
content/en/platform/corda/5.1/deploying-operating/vnodes/state.md
content/en/platform/corda/5.1/deploying-operating/vnodes/upgrade-cpi.md
content/en/platform/corda/5.1/developing-applications/getting-started/running-your-first-cordapp/_index.md
content/en/platform/corda/5.1/developing-applications/getting-started/utxo-ledger-example-cordapp/running-the-chat-cordapp/_index.md
content/en/platform/corda/5.1/developing-applications/packaging/code-signing/custom-cert.md
content/en/platform/corda/5.1/reference/rest-api/accessing.md

Preview: https://niamh.preview.docs.r3.com/en/platform/corda/5.1.html

/api/v1 -> /api/v5_1

---

content/en/platform/corda/5.1/developing-applications/api/ledger/utxo-ledger/token-selection/_index.md
content/en/platform/corda/5.1/developing-applications/api/ledger/utxo-ledger/token-selection/using.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.1/developing-applications/api/ledger/utxo-ledger.html

add UtxoTokenTransactionStateObserver

---

content/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/deploying/manual-bootstrapping.html

Add extra datasource properties to db bootstrap config

---

content/en/api-ref/_index.md
content/en/platform/corda/_index.md
themes/doks/layouts/index.html

Preview https://nadine.preview.docs.r3.com/

Update versioning for 5.1

---

.ci/algolia/requirements.txt
content/en/api-ref/api-ref-corda-4.md
content/en/platform/corda/1.5/cenm/cenm-support-matrix.md
content/en/platform/corda/1.5/cenm/legal-info-1.5.9.html
content/en/platform/corda/1.5/cenm/release-checksum-cenm.md
content/en/platform/corda/1.5/cenm/release-notes.md
content/en/platform/corda/5.0/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.0/key-concepts/cordapp-dev/building/_index.md
content/en/platform/corda/5.0/key-concepts/fundamentals/_index.md
content/en/platform/corda/5.0/key-concepts/fundamentals/application-networks/_index.md
layouts/partials/defs-field-desc-ref-docs.html
layouts/partials/field-desc-ref-docs.html
layouts/partials/referenced-field-desc-ref-docs.html
package-lock.json
package.json
themes/doks/layouts/shortcodes/tooltip.html

Merge main into 5.1

---

content/en/platform/corda/4.11/enterprise/node/operating/maintenance-mode.md

Preview at:
https://paul.preview.docs.r3.com/en/platform/corda/4.11/enterprise/node/operating/maintenance-mode.html

DOC-5722 - added details on configuring ledger recovery cleanup job

---

content/en/platform/corda/5.1/application-networks/creating/members/cpi.md
content/en/platform/corda/5.1/application-networks/creating/mgm/cpi.md
content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/deploying.html#p2p-gateway

Ingress for P2P gateway

---

themes/doks/assets/scss/layouts/_home.scss
themes/doks/layouts/index.html
themes/doks/layouts/partials/header/header.html

- Remove temporary alert banner: https://r3-cev.atlassian.net/browse/DOC-5965
- Reduce height of homepage search,etc: https://r3-cev.atlassian.net/browse/DOC-5937

Make better use of space on home page

---

themes/doks/assets/scss/common/_global.scss
themes/doks/layouts/partials/header/header.html

See preview of fix: https://colin.preview.docs.r3.com/en/platform/corda/5.0/key-concepts.html

Fix breadcrumb issue when no alert banner message displayed

---

content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/deploying.html#replica-counts

update config for segregated workers

---

content/en/platform/corda/5.1/developing-applications/getting-started/first-flow/code-java.md
content/en/platform/corda/5.1/glossaryitems.json

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/reference/glossary.html

Update glossary for new flow workers

---

themes/doks/layouts/_default/baseof.html
themes/doks/layouts/partials/head/head.html

Caching the recommended Hugo partials to help improve build performance. See Jira for before and after metrics.

Cache the recommended partials

---

content/en/platform/corda/5.0/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/mgm/cpi.md
content/en/platform/corda/5.0/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.0/application-networks/creating/mgm/register.md
content/en/platform/corda/5.0/application-networks/creating/optional/session-certificates.md
content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
content/en/platform/corda/5.0/glossaryitems.json

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.0.html

Add PEM and CSR glossary items

---

content/en/platform/corda/4.11/community/release-notes.md
content/en/platform/corda/4.11/enterprise/release-notes-enterprise.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.11/community/release-notes.html#database-schema-changes

Updated node migration scripts in CE 4.11 release notes

---

content/en/tools-corda5/csde/_index.md

https://nadine.preview.docs.r3.com/

Add alias for moved CSDE content

---

content/en/platform/corda/4.11/community/release-notes.md
content/en/platform/corda/4.11/enterprise/release-notes-enterprise.md

Preview: https://neil.preview.docs.r3.com/en/platform/corda/4.11/enterprise/release-notes-enterprise.html#upgraded-dependencies

DOC-5543: Databases upgrades

---

content/en/platform/corda/1.4/cenm/cenm-error-codes.md
content/en/platform/corda/1.5/cenm/cenm-error-codes.md
content/en/platform/corda/4.10/community/cli-ux-guidelines.md
content/en/platform/corda/4.10/enterprise/cordapps/database-management.md
content/en/platform/corda/4.7/enterprise/cordapps/database-management.md
content/en/platform/corda/4.8/enterprise/cordapps/database-management.md
content/en/platform/corda/4.9/enterprise/cordapps/database-management.md
content/en/platform/corda/5.0/deploying-operating/config/fields/p2p-LinkManager.md
content/en/platform/corda/5.0/developing-applications/api/ledger/_index.md
themes/doks/layouts/index.html

Preview: https://colin.preview.docs.r3.com/

Merge main to 5.1

---

content/en/platform/corda/5.1/deploying-operating/config/fields/vnodeDatasource.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/config/fields/vnodedatasource.html

vnode.datasource config section

---

content/en/platform/corda/5.0/deploying-operating/config/security-policies.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.0/deploying-operating/config/security-policies.html

5.0: Edits to "Security Policies" for clarity 

---

content/en/platform/corda/5.1/deploying-operating/config/security-policies.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/config/security-policies.html

Edits to "Security Policies" for clarity

---

content/en/platform/corda/5.1/deploying-operating/config/fields/vnodeDatasource.md
content/en/platform/corda/5.1/release-notes/5.1.0.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.1/release-notes/5.1.0.html

Clarify useAndRelease in Release Notes

---

themes/doks/assets/snippets/corda-5.0/end-of-life-corda5.md

Preview: https://docs.preview.docs.r3.com/en/platform/corda/eol-schedule.html

Update eol 5.1 dates

---

content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md

https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/deploying.html#p2p-gateway

Add Network Operator links for Ingress for the P2P gateway worker

---

themes/doks/assets/scss/common/_global.scss
themes/doks/layouts/partials/header/header.html

https://nadine.preview.docs.r3.com/

add banner for 5.1 release

---

content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/deploying.html#container-images-for-corda-enterprise

Rename Enterprise tar

---

content/en/platform/corda/5.1/_index.md

https://nadine.preview.docs.r3.com/en/platform/corda.html

change order in menu for 5.1

---

content/en/platform/corda/5.0/release-notes/5.0.1.md
content/en/platform/corda/5.0/release-notes/legal-info/corda-gradle-plugins.html

https://nadine.preview.docs.r3.com/en/platform/corda/5.0/release-notes.html

5.0.1 patch

---

content/en/platform/corda/5.0/application-networks/creating/members/cpi.md
content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
content/en/tools-corda5/csde/installing/_index.md
themes/doks/assets/snippets/corda-5.0/installing-corda-cli.md
themes/doks/layouts/shortcodes/enterprise-icon.html

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.0.html

5.0.1 updates

---

content/en/platform/corda/5.0/developing-applications/basic-cordapp/flows.md
content/en/platform/corda/5.1/developing-applications/basic-cordapp/flows.md

https://nadine.preview.docs.r3.com/en/platform/corda/5.1/developing-applications/basic-cordapp/flows.html

Remove tooltips from note blocks

---

themes/doks/layouts/partials/head/featured-image.html
themes/doks/layouts/partials/head/opengraph.html
themes/doks/layouts/partials/head/twitter_cards.html

- The title is the text displayed as the link in link previews generated for the page
- Modified position of text on images generated for Open Graph meta data

Update Open Graph title to include version

---

content/en/platform/corda/4.11/enterprise/ledger-recovery-flow.md
content/en/platform/corda/4.11/enterprise/node/collaborative-recovery/ledger-recovery/archiving.md
content/en/tools/archiving-service/archiving-service-index.md

CE Archiving preview: https://anna.preview.docs.r3.com/en/platform/corda/4.11/enterprise/node/collaborative-recovery/ledger-recovery/archiving.html
Postgres and Oracle preview: https://anna.preview.docs.r3.com/en/tools/archiving-service/archiving-service-index.html#postgres

DOC-6271: Updated the Archive Service content

---

content/en/platform/corda/5.2/application-networks/creating/mgm/endpoints.md
content/en/platform/corda/5.2/application-networks/creating/mgm/reregister.md
content/en/platform/corda/5.2/application-networks/upgrading/_index.md

Preview: 
https://nadine.preview.docs.r3.com/en/platform/corda/5.2/application-networks/creating/mgm/endpoints.html
https://nadine.preview.docs.r3.com/en/platform/corda/5.2/application-networks/creating/mgm/reregister.html

MGM Re-registration

---

content/en/platform/corda/4.11/enterprise/node/setup/corda-configuration-fields.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/4.11/enterprise/node/setup/corda-configuration-fields.html

DOC-6165: Changed H2 to H3 to avoid Algolia error

---

content/en/platform/corda/5.2/reference/rest-api/openapi_source.json

Update with latest REST API spec

latest API spec

---

content/en/platform/corda/5.1/developing-applications/api/ledger/utxo-ledger/vault-queries.md

Copy changes from https://github.com/corda/corda-docs-portal/pull/2012 (5.2) to 5.1.
Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.1/developing-applications/api/ledger/utxo-ledger/vault-queries.html

5.1: Edits to existing vault-named queries content

---

content/en/platform/corda/5.2/deploying-operating/config/fields/rbac.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.2/deploying-operating/config/fields/rbac.html

Add rbac config file

---

content/en/platform/corda/5.2/application-networks/creating/optional/mutual-tls-connections.md
content/en/platform/corda/5.2/application-networks/managing/registration-requests/configuring-manual-approval-rules.md
content/en/platform/corda/5.2/application-networks/managing/registration-requests/pre-auth/configuring-pre-auth-rules.md
content/en/platform/corda/5.2/application-networks/managing/registration-requests/pre-auth/preauthenticating-tokens.md
content/en/platform/corda/5.2/application-networks/managing/registration-requests/reviewing-registration-requests.md
themes/doks/assets/snippets/corda-5.2/installing-corda-cli.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.2/application-networks/managing/registration-requests.html

Add powershell examples to "Managing Member Registrations"

---

themes/doks/assets/scss/common/_global.scss

Preview example: https://neil.preview.docs.r3.com/en/platform/corda/5.1/key-concepts.html

Add bullets to generated TOCs

---

content/en/platform/corda/4.12/community/_index.md
content/en/platform/corda/4.12/enterprise/_index.md
content/en/platform/corda/4.12/enterprise/api-core-types.md

Preview: https://anna.preview.docs.r3.com/

DOC-6327: Added cascade to ENT and OS index files

---

themes/doks/assets/snippets/corda-5.2/end-of-life-corda5.md
themes/doks/assets/snippets/corda-5.2/prereqs-container.md
themes/doks/assets/snippets/corda-5.2/prereqs-databases.md
themes/doks/assets/snippets/corda-5.2/prereqs-messaging.md
themes/doks/assets/snippets/corda-5.2/prereqs-vault.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/release-notes/support.html

Update platform support for 5.2

---

content/en/platform/corda/5.1/key-concepts/_index.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/key-concepts.html

Key Concepts formatting fix

---

themes/doks/assets/scss/common/_global.scss
themes/doks/layouts/shortcodes/toc.html

Preview: https://colin.preview.docs.r3.com/
Made CSS change local to toc shortcode

Revert toc CSS change - unexpected change to C4 side nav

---

content/en/platform/corda/5.2/application-networks/creating/mgm/reregister.md
content/en/platform/corda/5.2/application-networks/upgrading/_index.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.2/application-networks/upgrading.html

5.2 Network Upgrade updates

---

content/en/platform/corda/5.2/release-notes/5.2.md

Preview: https://niamh.preview.docs.r3.com/en/platform/corda/5.2/release-notes/5.2.html

First batch of 5.2 Release Notes

---

content/en/platform/corda/5.2/application-networks/creating/members/cpi.md
content/en/platform/corda/5.2/application-networks/upgrading/_index.md
content/en/platform/corda/5.2/deploying-operating/deployment/deploying/_index.md

Also fixed version nums for https://r3-cev.atlassian.net/browse/DOC-6224

5.2: Remove links to Developer Portal

---

content/en/platform/corda/5.2/release-notes/5.2.md

Includes https://r3-cev.atlassian.net/browse/DOC-6354

Add performance note and fix broken links

---

themes/doks/assets/scss/common/_global.scss

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1.html

Update bottom margin on nested bullets

---

content/en/platform/corda/5.1/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.1/application-networks/creating/members/reregister.md
content/en/platform/corda/5.1/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.1/application-networks/creating/notaries.md
content/en/platform/corda/5.1/deploying-operating/deployment/deploying/_index.md
themes/doks/assets/scss/common/_global.scss

Merge main to 5.2

---

content/en/platform/corda/5.2/deploying-operating/deployment/deploying/_index.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/deploying-operating/deployment/deploying.html

State Manager DB Updates

---

content/en/platform/corda/5.1/reference/corda-cli/vnode.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/reference/corda-cli/vnode.html

add warning for `reset` command

---

content/en/platform/corda/5.1/glossaryitems.json

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/reference/glossary.html

5.2 Glossary: add links

---

content/en/platform/corda/5.2/glossaryitems.json

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/reference/glossary.html

5.2 Glossary: update links

---

content/en/platform/corda/4.10/community/error-codes.md
content/en/platform/corda/4.11/community/_index.md
content/en/platform/corda/4.11/community/api-identity.md
content/en/platform/corda/4.11/community/api-persistence.md
content/en/platform/corda/4.11/community/api-rpc.md
content/en/platform/corda/4.11/community/api-states.md
content/en/platform/corda/4.11/community/error-codes.md
content/en/platform/corda/4.11/community/get-started/tutorials/supplementary-tutorials/event-scheduling.md
content/en/platform/corda/4.11/community/get-started/tutorials/supplementary-tutorials/tutorial-clientrpc-api.md
content/en/platform/corda/4.11/community/get-started/tutorials/supplementary-tutorials/tutorial-observer-nodes.md
content/en/platform/corda/4.11/community/network-bootstrapper.md
content/en/platform/corda/4.11/enterprise/_index.md
content/en/platform/corda/4.11/enterprise/cordapps/cordapp-build-systems.md
content/en/platform/corda/4.11/enterprise/notary-healthcheck.md
content/en/platform/corda/4.8/enterprise/node/operating/clientrpc.md
content/en/platform/corda/4.9/community/error-codes.md

Added aliases to cover the main ones a search shows up. Apart from error codes, have ignored anything with versions no longer supported.

DOC-6380 - Added aliases required by codebase

---

content/en/platform/corda/5.1/application-networks/creating/members/key-pairs.md
content/en/platform/corda/5.1/application-networks/creating/mgm/key-pairs.md
content/en/platform/corda/5.1/application-networks/creating/optional/session-certificates.md

Update to omitting root certificate

---

content/en/platform/corda/5.1/deploying-operating/deployment/prerequisites.md
themes/doks/assets/snippets/corda-5.1/prereqs-container.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/prerequisites.html#container-orchestration

Set helm prerequisite version 

---

content/en/platform/corda/5.2/deploying-operating/keys/_index.md
content/en/platform/corda/5.2/release-notes/5.2.md

5.2: No rotation of P2P wrapping key

---

content/en/platform/corda/5.2/deploying-operating/deployment/deploying/_index.md
content/en/platform/corda/5.2/developing-applications/ledger/ledger-repair.md
content/en/platform/corda/5.2/release-notes/5.2.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/release-notes/5.2.html#ledger-repair-functionality

5.2: Ledger repair functionality

---

content/en/platform/corda/5.2/reference/rest-api/openapi_source.json

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/reference/rest-api.html

5.2 GA: Update REST API docs

---

content/en/platform/corda/5.2/release-notes/5.2.md
content/en/tools-corda5/contract-testing/_index.md
content/en/tools-corda5/contract-testing/building.md
content/en/tools-corda5/contract-testing/examples.md
content/en/tools-corda5/contract-testing/importing.md
content/en/tools-corda5/contract-testing/service-injection.md

Preview: https://nadine.preview.docs.r3.com/en/tools-corda5/contract-testing.html

Contract Testing Updates: version 2

---

content/en/platform/corda/5.2/release-notes/legal-info/corda-api.html
content/en/platform/corda/5.2/release-notes/legal-info/corda-cli.html
content/en/platform/corda/5.2/release-notes/legal-info/corda-runtime-os.html
content/en/platform/corda/5.2/release-notes/legal-info/corda5-enterprise.html
content/en/tools-corda5/contract-testing/service-injection.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/release-notes/legal-info.html

5.2: add TPN files

---

content/en/platform/corda/5.2/release-notes/5.2.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.2/release-notes/5.2.html#cordapp-development

Token Selection API Idempotency

---

content/en/platform/corda/5.2/deploying-operating/keys/_index.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.2/deploying-operating/keys.html

Remove the Cluster level keys info

---

themes/doks/layouts/_default/list.html
themes/doks/layouts/_default/single.html

Move comments to correct blank page issue.

---

content/en/platform/corda/5.3/reference/corda-cli/cpi.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.3/reference/corda-cli/cpi.html

DOC-6384: New Corda CLI cpi command

---

content/en/platform/corda/5.3/developing-applications/api/ledger/utxo-ledger/token-selection/_index.md
content/en/platform/corda/5.3/developing-applications/api/ledger/utxo-ledger/token-selection/using.md

Preview: https://amie.preview.docs.r3.com/en/platform/corda/5.3/developing-applications/api/ledger/utxo-ledger/token-selection.html

DOC-6294: Preferential token selection

---

content/en/platform/corda/5.2/developing-applications/packaging/code-signing/signing-cli.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.2/developing-applications/packaging/code-signing/signing-cli.html

DOC-6449: Exporting and importing signing key into the key store

---

content/en/platform/corda/5.2/reference/corda-cli/upgrade.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.2/reference/corda-cli/upgrade.html

DOC-6453: Added the 5.2.1 upgrade CLI command

---

content/en/platform/corda/5.2/release-notes/legal-info/corda-api.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/_index.md
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda-api.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda-cli.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda-runtime-os.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda5-enterprise.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/_index.md
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-api.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-cli.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-enterprise.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-runtime.html

https://nadine.preview.docs.r3.com/en/platform/corda/5.2/release-notes/legal-info/legal-info-521.html

DOC-6458: Corda 5.2.1 legal info

---

content/en/platform/corda/5.2/deploying-operating/deployment/upgrading/_index.md
content/en/platform/corda/5.2/deploying-operating/deployment/upgrading521/_index.md
content/en/platform/corda/5.2/deploying-operating/deployment/upgrading521/rolling-back521.md
content/en/platform/corda/5.2/reference/corda-cli/upgrade.md
content/en/platform/corda/5.2/release-notes/5.2.md
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/_index.md
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda-api.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda-cli.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda-runtime-os.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-52/corda5-enterprise.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/_index.md
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-api.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-cli.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-enterprise.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-521/corda521-runtime.html
themes/doks/assets/snippets/corda-5.2/installing-corda-cli.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.2/release-notes/5.2.html

5.2.1 branch merge into main

---

content/en/platform/corda/4.12/enterprise/node/operating/tvu/tvu-cli-examples.md

Preview: https://niamh.preview.docs.r3.com/en/platform/corda/4.12/enterprise/node/operating/tvu/tvu-cli-examples.html#progress-reloading

DOC-6441: Added a note about TVU progress reloading

---

content/en/platform/corda/5.3/deploying-operating/config-users/creating-users.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.3/deploying-operating/config-users/creating-users.html#creating-users

DOC-6437: Updated managing users and roles info

---

content/en/platform/corda/1.6/cenm/backup-recommendations.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/1.6/cenm/backup-recommendations.html

DOC-6193: CENM backup recommendations

---

content/en/tools/archiving-service/checksums-archiving.md
content/en/tools/archiving-service/legal-info/legal-info-archiving-1.2.md
content/en/tools/ledgergraph/ledgergraph-checksums.md
content/en/tools/ledgergraph/legal-info/legal-info-ledgergraph-1.3.md

Preview: https://nadine.preview.docs.r3.com/en/tools/archiving-service/checksums-archiving.html

DOC-6476: Linked Archive Service and LedgerGraph to checksums and legal info

---

content/en/platform/corda/4.12/community/release-platform-support-matrix.md
content/en/platform/corda/4.12/enterprise/platform-support-matrix.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.12/community/release-platform-support-matrix.html

DOC-6484: Updated Corda OS support matrix

---

content/en/platform/corda/5.3/deploying-operating/config-users/creating-users.md
content/en/platform/corda/5.3/reference/rest-api/openapi_source.json

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.3/deploying-operating/config-users/creating-users.html#deleting-users

DOC-6479: Added endpoint for deleting users

---

content/en/platform/corda/5.3/reference/corda-cli/profile.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.3/reference/corda-cli/profile.html

DOC-6466: Added profile CLI command

---

content/en/platform/corda/5.3/deploying-operating/config-users/creating-users.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.3/deploying-operating/config-users/creating-users.html#managing-user-properties

DOC-6490: Added Managing User Properties section

---

content/en/platform/corda/4.12/enterprise/node/operating/tvu/_index.md
content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md

Preview rel notes: https://anna.preview.docs.r3.com/en/platform/corda/4.12/enterprise/release-notes-enterprise.html#upgrade-recommendation
Preview TVU page: https://anna.preview.docs.r3.com/en/platform/corda/4.12/enterprise/node/operating/tvu.html

DOC-6511: Added important notes to TVU content

---

content/en/platform/corda/4.11/community/release-notes.md
content/en/platform/corda/4.11/enterprise/release-notes-enterprise.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.11/enterprise/release-notes-enterprise.html#corda-enterprise-edition-4114-release-notes

DOC-6512: Added Corda 4.11.4 patch release notes

---

content/en/platform/corda/5.3/deploying-operating/config-users/creating-users.md
content/en/platform/corda/5.3/deploying-operating/config-users/rbac-groups.md

Preview _Managing RBAC Groups_ page: https://anna.preview.docs.r3.com/en/platform/corda/5.3/deploying-operating/config-users/rbac-groups.html
Preview _Setting Parent Group for Users_ section: https://anna.preview.docs.r3.com/en/platform/corda/5.3/deploying-operating/config-users/creating-users.html#setting-parent-group-for-users

DOC-6478: Managing RBAC groups

---

content/en/platform/corda/5.1/application-networks/creating/members/cpi.md
content/en/platform/corda/5.2/application-networks/creating/members/cpi.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.2/application-networks/creating/members/cpi.html#import-the-notary-certificate

DOC-6537: Import notary cert

---

content/en/platform/corda/4.8/enterprise/release-notes-enterprise.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.8/enterprise/release-notes-enterprise.html

DOC-6543: Added 4.8.12 release notes

---

content/en/platform/corda/1.6/cenm/zone-service.md

Preview: https://nadine.preview.docs.r3.com/en/platform/corda/1.6/cenm/zone-service.html

DOC: 6538: Update zone service page to mention config file

---

content/en/platform/corda/1.6/cenm/config-identity-manager-parameters.md
content/en/platform/corda/1.6/cenm/config-network-map-parameters.md
content/en/platform/corda/1.6/cenm/config-shell.md
content/en/platform/corda/1.6/cenm/signing-service.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/config-shell.html

DOC-6493: Add host options

---

content/en/platform/corda/1.6/cenm/config-zone-service-parameters.md

Preview: https://colin.preview.docs.r3.com/en/platform/corda/1.6/cenm/config-zone-service-parameters.html

DOC-6508: Added Zone Service config params page

---

content/en/platform/corda/1.6/cenm/release-notes.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/release-notes.html

DOC-6506: Added CENM 1.6.1 release notes

---

content/en/platform/corda/1.6/cenm/cenm-support-matrix.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/cenm-support-matrix.html

DOC-6557: CENM 1.6.1 support matrix updates

---

content/en/platform/corda/1.6/cenm/cenm-support-matrix.md
content/en/platform/corda/1.6/cenm/release-notes.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/release-notes.html

DOC-6558: Added info to the upgraded dependencies rel notes section

---

content/en/platform/corda/4.12/enterprise/node/operating/tvu/running-tvu.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.12/enterprise/node/operating/tvu/running-tvu.html

DOC-6565: Added Running the TVU section

---

content/en/platform/corda/4.12/community/release-notes.md
content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md

Preview OS: https://niamh.preview.docs.r3.com/en/platform/corda/4.12/community/release-notes.html#corda-open-source-edition-4122-release-notes
Preview ENT: https://niamh.preview.docs.r3.com/en/platform/corda/4.12/enterprise/release-notes-enterprise.html#corda-enterprise-edition-4122-release-notes

DOC-6566: Corda 4.12.2 release notes

---

content/en/platform/corda/5.2/release-notes/legal-info/legal-info-522/_index.md
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-522/corda522-api.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-522/corda522-cli.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-522/corda522-enterprise.html
content/en/platform/corda/5.2/release-notes/legal-info/legal-info-522/corda522-runtime.html

Preview: https://neil.preview.docs.r3.com/en/platform/corda/5.2/release-notes/legal-info/legal-info-522.html

DOC-6575: Corda 5.2.2 legal info

---

content/en/platform/corda/4.12/community/legal-info/legal-info-4.12.3.html
content/en/platform/corda/4.12/community/release-checksum-os.md
content/en/platform/corda/4.12/community/release-notes.md
content/en/platform/corda/4.12/enterprise/legal-info/legal-info-4.12.3.html
content/en/platform/corda/4.12/enterprise/release-checksum-enterprise.md
content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md

OS release notes preview: https://anna.preview.docs.r3.com/en/platform/corda/4.12/community/release-notes.html#corda-open-source-edition-4123-release-notes
ENT release notes preview: https://anna.preview.docs.r3.com/en/platform/corda/4.12/enterprise/release-notes-enterprise.html#corda-enterprise-edition-4123-release-notes

DOC-6576: Corda 4.12.3 patch release

---

content/en/platform/corda/1.6/cenm/config-angel-service-parameters.md

Preview: https://niamh.preview.docs.r3.com/en/platform/corda/1.6/cenm/config-angel-service-parameters.html

DOC-6584: Added two additional Angel Service params

---

content/en/platform/corda/4.9/enterprise/legal-info/legal-info-4.9.10.html
content/en/platform/corda/4.9/enterprise/legal-info/legal-info-4.9.11.html
content/en/platform/corda/4.9/enterprise/release-checksum-enterprise.md
content/en/platform/corda/4.9/enterprise/release-notes-enterprise.md

ENT rel notes peview: https://anna.preview.docs.r3.com/en/platform/corda/4.9/enterprise/release-notes-enterprise.html#corda-enterprise-edition-4911-release-notes
OS has been archived. No release notes needed.

DOC-6579: Corda 4.9.11 patch release documentation

---

content/en/platform/corda/4.11/community/legal-info/legal-info-4.11.4.html
content/en/platform/corda/4.11/community/legal-info/legal-info-4.11.5.html
content/en/platform/corda/4.11/community/release-checksum-os.md
content/en/platform/corda/4.11/community/release-notes.md
content/en/platform/corda/4.11/enterprise/legal-info/legal-info-4.11.4.html
content/en/platform/corda/4.11/enterprise/legal-info/legal-info-4.11.5.html
content/en/platform/corda/4.11/enterprise/release-checksum-enterprise.md
content/en/platform/corda/4.11/enterprise/release-notes-enterprise.md

ENT rel notes preview: https://colin.preview.docs.r3.com/en/platform/corda/4.11/enterprise/release-notes-enterprise.html#corda-enterprise-edition-4115-release-notes
OS rel notes preview: https://colin.preview.docs.r3.com/en/platform/corda/4.11/community/release-notes.html#corda-community-edition-4115-release-notes

DOC-6581: Corda 4.11.5 patch release documentation

---

content/en/platform/corda/1.6/cenm/config-pki-tool-parameters.md
content/en/platform/corda/1.6/cenm/enm-with-ssl.md
content/en/platform/corda/1.6/cenm/pki-tool.md
content/en/platform/corda/1.6/cenm/release-notes.md
content/en/platform/corda/1.6/cenm/signing-service.md

Previews of the updated sections:
- Release note: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/release-notes.html
- Azure Key Vault HSM Key Store Configuration: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/config-pki-tool-parameters.html#azure-key-vault-hsm-key-store-configuration
- Azure Key Vault HSM Configuration Using MSAL: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/pki-tool.html#azure-key-vault-hsm-configuration-using-msal
- Azure Key Vault: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/signing-service.html#azure-key-vault

DOC-6586: Microsoft Authentication Library (MSAL)

---

content/en/platform/corda/1.6/cenm/config-angel-service-parameters.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/config-angel-service-parameters.html

DOC-6588: Updated Angel Service params

---

content/en/platform/corda/4.12/community/release-platform-support-matrix.md
content/en/platform/corda/4.12/enterprise/platform-support-matrix.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.12/enterprise/platform-support-matrix.html

DOC-6590: Added Red Hat Enterprise Linux version plus some edits

---

content/en/platform/corda/4.12/community/release-notes.md
content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.12/enterprise/release-notes-enterprise.html

DOC-6592: Added ENT and OS release notes

---

content/en/about-the-docs/_index.md
content/en/platform/corda/eol-schedule.md
themes/doks/assets/snippets/corda-4/end-of-life-corda4.md

Preview: https://amie.preview.docs.r3.com/en/platform/corda/eol-schedule.html

DOC-6594: Updated the EOL strategy for Corda 4

---

content/en/platform/corda/4.12/community/corda-configuration-fields.md
content/en/platform/corda/4.12/community/legal-info/legal-info-4.12.5.html
content/en/platform/corda/4.12/community/release-checksum-os.md
content/en/platform/corda/4.12/community/release-notes.md
content/en/platform/corda/4.12/enterprise/legal-info/legal-info-4.12.5.html
content/en/platform/corda/4.12/enterprise/node/setup/corda-configuration-fields.md
content/en/platform/corda/4.12/enterprise/release-checksum-enterprise.md
content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/4.12/enterprise/release-notes-enterprise.html

Merge 4.12.5 content into main

---

content/en/platform/corda/1.6/cenm/legal-info/_index.md
content/en/platform/corda/1.6/cenm/legal-info/legal-info-1.6.1.html
content/en/platform/corda/1.6/cenm/legal-info/legal-info-1.6.html
content/en/platform/corda/1.6/cenm/release-checksum-cenm.md
content/en/platform/corda/1.6/cenm/release-notes.md
content/en/platform/corda/4.12/enterprise/release-notes-enterprise.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/legal-info/legal-info-1.6.html

DOC-6595: Added checksums and legal info

---

content/en/platform/corda/1.6/cenm/_index.md
content/en/platform/corda/1.6/cenm/angel-service.md
content/en/platform/corda/1.6/cenm/cenm-support-matrix.md
content/en/platform/corda/1.6/cenm/config-angel-service-parameters.md
content/en/platform/corda/1.6/cenm/config-identity-manager-parameters.md
content/en/platform/corda/1.6/cenm/config-network-map-parameters.md
content/en/platform/corda/1.6/cenm/config-pki-tool-parameters.md
content/en/platform/corda/1.6/cenm/config-shell.md
content/en/platform/corda/1.6/cenm/config-zone-service-parameters.md
content/en/platform/corda/1.6/cenm/enm-with-ssl.md
content/en/platform/corda/1.6/cenm/legal-info/_index.md
content/en/platform/corda/1.6/cenm/legal-info/legal-info-1.6.1.html
content/en/platform/corda/1.6/cenm/legal-info/legal-info-1.6.html
content/en/platform/corda/1.6/cenm/pki-tool.md
content/en/platform/corda/1.6/cenm/release-checksum-cenm.md
content/en/platform/corda/1.6/cenm/release-notes.md
content/en/platform/corda/1.6/cenm/signing-service.md
content/en/platform/corda/1.6/cenm/zone-service.md

Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm.html

Merge CENM 1.6.1 docs

---

content/en/archived-docs/CENM/1.1/pki-tool.md
content/en/platform/corda/1.6/cenm/config-pki-tool-parameters.md
content/en/platform/corda/1.6/cenm/legal-info/legal-info-1.6.2.html
content/en/platform/corda/1.6/cenm/pki-tool.md
content/en/platform/corda/1.6/cenm/release-checksum-cenm.md
content/en/platform/corda/1.6/cenm/release-notes.md
content/en/platform/corda/1.6/cenm/signing-service.md

Add docs for CENM 1.6.2 release.
Preview: https://anna.preview.docs.r3.com/en/platform/corda/1.6/cenm/release-notes.html

ENT-12822: Add CENM 1.6.2 release notes

---

content/en/platform/corda/1.6/cenm/config-pki-tool-parameters.md
content/en/platform/corda/1.6/cenm/legal-info/legal-info-1.6.2.html
content/en/platform/corda/1.6/cenm/pki-tool.md
content/en/platform/corda/1.6/cenm/release-checksum-cenm.md
content/en/platform/corda/1.6/cenm/release-notes.md
content/en/platform/corda/1.6/cenm/signing-service.md

Add docs for CENM 1.6.2 release.

ENT-12822: Add docs for CENM 1.6.2

---

content/en/platform/corda/4.10/enterprise/key-concepts-contracts.md
content/en/platform/corda/4.11/enterprise/cordapps/database-management.md
content/en/platform/corda/4.11/enterprise/key-concepts-contracts.md
content/en/platform/corda/4.12/enterprise/cordapps/database-management.md
content/en/platform/corda/4.12/enterprise/key-concepts-contracts.md
content/en/platform/corda/4.8/enterprise/cordapps/database-management.md
content/en/platform/corda/4.9/enterprise/cordapps/database-management.md
content/en/platform/corda/4.9/enterprise/key-concepts-flows.md
content/en/tools/tokens-sdk/legal-info-1.2.5.html

Invalid date formats cause issues with recent versions of Hugo.

DOC-6618 - fixed date formats

---

content/en/platform/corda/4.10/enterprise/notary/upgrading-the-ha-notary-service.md
content/en/platform/corda/4.11/enterprise/notary/upgrading-the-ha-notary-service.md
content/en/platform/corda/4.12/enterprise/notary/upgrading-the-ha-notary-service.md
content/en/platform/corda/4.8/enterprise/notary/upgrading-the-ha-notary-service.md
content/en/platform/corda/4.9/enterprise/notary/upgrading-the-ha-notary-service.md

Making upgrade instructions future proof

DOC-6681 - ha notary upgrade (main)

---

content/en/platform/corda/4.10/community/api-core-types.md
content/en/platform/corda/4.10/enterprise/api-core-types.md
content/en/platform/corda/4.11/community/api-core-types.md
content/en/platform/corda/4.11/enterprise/api-core-types.md
content/en/platform/corda/4.12/community/api-core-types.md
content/en/platform/corda/4.12/enterprise/api-core-types.md
content/en/platform/corda/4.8/enterprise/api-core-types.md
content/en/platform/corda/4.9/enterprise/api-core-types.md

DOC-6664 - api core
