corda/corda-docs-portal

- config.toml
- content/en/announcements/_index.md
- content/en/apps/bankinabox/bank-index.md
- content/en/apps/reissuance/state-reissuance.md
- content/en/platform/conclave/_index.md
- content/en/release-notes/_index.md
- content/en/tools/ledgergraph/ledgergraph-index.md
- themes/doks/assets/js/vendor/googleanalytics.js
- themes/doks/static/js/home.js
* DOC-3121 Updated GA code
* DOC-3331 Fixed some typos and links in Announcements page
* DOC-3330 Updated tools > ledgergraph page - capitalisation and a broken link
* DOC-3326 Updated state reissuance page in Apps section - removed RHS context menu, fixed a link, and updated front matterin bankinabox-index
* DOC-3325 Removed "home" link in LHS context menu in conclave and releases sections as these are single static pages with no child pages
* DOC-3327 Disabled autoplay for carousel slides
> DOC-3121 DOC-3331 DOC-3330 DOC-3326 DOC-3325 DOC-3327 Various fixes

- makefile
* do not try to rebuild `prod-hugo-build` depending if there are changes
in the sources. Nobody really uses it.
* use `make clean prod-hugo-build` instead
> NOTICK: remove obsolete dependency

- content/en/platform/corda/4.6/open-source/api-scanner.md
- content/en/platform/corda/4.6/open-source/business-network-membership.md
- content/en/platform/corda/4.6/open-source/cli-application-shell-extensions.md
- content/en/platform/corda/4.6/open-source/cli-ux-guidelines.md
- content/en/platform/corda/4.6/open-source/contributing-flow-state-machines.md
- content/en/platform/corda/4.6/open-source/contributing.md
- content/en/platform/corda/4.6/open-source/docker-image.md
- content/en/platform/corda/4.6/open-source/network-map.md
- content/en/platform/corda/4.6/open-source/running-a-notary.md
- content/en/platform/corda/4.6/open-source/setting-up-a-dynamic-compatibility-zone.md
- content/en/platform/corda/4.6/open-source/testing.md
Covers sections (header pages and child pages):
- Operations:
--> Networks
--> Official Corda Docker Image
--> Load testing
--> Shell extensions for CLI Applications
- Corda Network Foundations
- Participate
> DOC-3363-3 Fix broken links in Corda OS 4.6 pages

- content/en/platform/corda/4.3/enterprise/platform-support-matrix.md
Quick bug fix - text was wrapping incorrectly in version number tables of the platform support matrix in Corda Enterprise 4.3.
> DOC-3564: Text wrapping incorrectly in version number tables

- themes/doks/layouts/partials/sidebar/versions.html
> .File.Dir on zero object.
> Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}
This is caused when moved lines where evaluated for 404.html and main
index.html page, when there was no context to work with.
This is a cosmetic change, however it was a misleading one when I was
looking for a root reason of a completely different issue.
> NOTICK: remove Hugo warning about `.File.Dir`

- content/en/platform/corda/4.7/enterprise/node/auth-service.md
- content/en/platform/corda/4.8/enterprise/node/auth-service.md
A user had trouble logging in to AzureAD; the solution was to use the ObjectID as initial-user-external-id, but this was not well-documented. Updated the README.md to provide clarity. There is a matching patch going into appeng-auth repo (but this one can be deployed independently; the functionality already exists).
> EG-4795 Providing better comamnd-line guidance on AzureAD vs internal auth

- themes/doks/layouts/index.html
The Corda 4 box now links directly to latest versions of OS, Enterprise, and CENM. Will need to be updated with releases.
> DOC-3710-1: Quick links to 4.x docs from landing page

- content/en/platform/corda/5.0-dev-preview-1/tutorials/building-cordapp/c5-basic-cordapp-running.md
- content/en/platform/corda/5.0-dev-preview-1/tutorials/run-demo-cordapp.md
We had a request on Slack to link to the Gradle plugins page from the tutorials. This will help the user see their options for packaging their CorDapp. They can use the Gradle plugin rather than using the CorDapp builder if it's more convenient. This should be linked in the sections where the user is instructed to use the CorDapp Builder and given as an alternative.
> DOC-3762: Add link to gradle plugin page from tutorials pages

- content/en/platform/corda/4.8/enterprise/operations/deployment/host-prereq.md
- content/en/platform/corda/4.8/enterprise/serialization.md
From the ticket:
"Turns out this is missing one critical step, which can be found only in Corda code itself. Without this critical step it does not work.
"/**
Provide a subclass of this via the [java.util.ServiceLoader] mechanism to be able to whitelist types for
serialisation that you cannot otherwise annotate. The name of the class must appear in a text file on the
classpath under the path META-INF/services/net.corda.core.serialization.SerializationWhitelist
*/""
> DOC-3865: Completing instructions on adding class to serialization whitelist

- content/en/platform/corda/4.8/enterprise/node/operating/node-administration.md
This ticket covers some reorganisation of the logging page, adding some missing essentials and moving sections. The ticket requests a full detailed guide to reading and interpreting logs -- a debugging guide is something that was discussed with @mnesbit but the conclusion was:
- Capacities are maxed out currently with platform development work and this kind of guide would require some time-costly collaboration with various stakeholders.
- It's a difficult thing to master and interpretation of the logs themselves depends on knowing a lot about Corda - maybe too high level for docs.r3.com.
- It is a good piece of work to take note of, so as part of closing the ticket off a separate ticket will be made regarding investigation about a full logging guide.
> DOC-3700: More detail on logging page

- content/en/platform/corda/4.9/community/release-notes.md
- content/en/platform/corda/4.9/enterprise/release-notes-enterprise.md
As requested by Alex Koller on Slack
> DOC-3988: added cress-ref for standalone shell from Release Notes

- content/en/platform/corda/5.0-dev-preview-2/developing/api/api-application.md
Adds a short description of each of the packages in the `application` module. The fully fledged documentation is generated from the kdocs, but this gives a quick overview of what each part is for.
> CORE-6299: Add a description of each package in the application module

- content/en/platform/corda/5.0-dev-preview-2/getting-started/fast-feedback-with-the-simulator/fast-feedback-with-the-simulator.md
After time digging into CSS, this turned out to not be a CSS file issue, but rather an error in the code style invoked in the markdown. Here is the old version followed by the fixed version:
> doc-4157-code-highlighting-issue

- themes/doks/assets/scss/components/_code.scss
Heading code style parameter added to override the global code style, without affecting the code style in regular content. In image, you can see that the regular content code is unaffected, but the headings are changed as discussed.
> doc-4165-code-heading-change

- content/en/platform/corda/4.8/enterprise/node/setup/host-prereq.md
- content/en/platform/corda/4.8/enterprise/platform-support-matrix.md
- content/en/platform/corda/4.8/enterprise/release-notes-enterprise.md
- content/en/platform/corda/4.9/enterprise/node/setup/host-prereq.md
- content/en/platform/corda/4.9/enterprise/platform-support-matrix.md
Updated references to Postgres 13.3 and changed to 13.8, including the 4.8.1 release notes.
> ENT-8792 - Fixed mentions of Postgres 13.3, should be 13.8

- content/en/platform/corda/4.9/enterprise/node/node-flow-hospital.md
Added the following:
Flow Management API
If you want to interact with the Flow Hospital programatically, use the Flow Management API described in [Querying flow data](https://github.com/corda/corda-docs-portal/compare/DOC-4329?expand=1#operating/querying-flow-data.html).
> DOC-4329 - Added link from 'Flow Hospital' to 'Querying flow data'

- content/en/platform/corda/5.0-alpha/deploying/troubleshooting/cluster-health.md
- content/en/platform/corda/5.0-alpha/deploying/troubleshooting/support-bundles.md
Add content to `cluster-health.md` (this section could equally be called "Troubleshooting Deployment"). Also added a section to the support bundles topic on setting log levels.
> DOC-4187 Add cluster-health.md

- content/en/platform/corda/4.8/enterprise/cordapps/cordapp-overview.md
- content/en/platform/corda/4.9/enterprise/cordapps/cordapp-overview.md
URL link in 4.8 not working in staging site.
> Revert "Doc 4335: Broken link fixed in What is a CorDapp?"

- content/en/platform/corda/5.0-beta/getting-started/prerequisites/prerequisites.md
Update CSDE docs to states that ports 5432, 7000 & 8888 should be reserved.
> Doc 4371: Update CSDE docs to states that ports 5432, 7000 & 8888 should be reserved 

- content/en/release-notes/eol.md
Updated end of support for Corda 4.7 from 12/2022 to 12/2023.
See 
https://r3-cev.atlassian.net/browse/ENT-8822
> ENT-8822 - Updated end of support for Corda 4.7 from 12/2022 to 12/2023.

- content/en/platform/corda/4.9/enterprise/cordapps/api-confidential-identity.md
- content/en/platform/corda/4.9/enterprise/cordapps/api-states.md
- content/en/platform/corda/4.9/enterprise/financial-model.md
- content/en/platform/corda/4.9/enterprise/json.md
- content/en/platform/corda/4.9/enterprise/network-bootstrapper.md
- content/en/platform/corda/4.9/enterprise/network/compatibility-zones.md
- content/en/platform/corda/4.9/enterprise/node-explorer.md
- content/en/platform/corda/4.9/enterprise/node/collaborative-recovery/ledger-recovery-automatic.md
- content/en/platform/corda/4.9/enterprise/node/operating/clientrpc.md
- content/en/platform/corda/4.9/enterprise/node/operating/monitoring-and-logging/metering-collector.md
- content/en/platform/corda/4.9/enterprise/node/operating/node-database-tables.md
- content/en/platform/corda/4.9/enterprise/node/operating/querying-flow-data.md
- content/en/platform/corda/4.9/enterprise/node/setup/corda-configuration-fields.md
- content/en/platform/corda/4.9/enterprise/operations/deployment/deployment-kubernetes.md
- content/en/platform/corda/4.9/enterprise/oracles.md
A fix where links to Open Source Edition docs broke when it was renamed Community Edition.
> DOC-4387  - replaced 'open-source' in 4.9 links with 'community'

- content/en/platform/corda/4.9/community/app-upgrade-notes.md
- content/en/platform/corda/4.9/community/versioning.md
- content/en/platform/corda/4.9/enterprise/app-upgrade-notes.md
Confirmed with @Adel El-Beik that no manual instructions are required for platform 11 (or indeed for platform 12, 4.10).
> DOC-4367 - Added missing info on platform version 11 for 4.9

- content/en/platform/corda/4.9/community/reissuing-states.md
Fixed broken link. Noted that 4.9 has a number of such links going to 4.8; I'll add a separate ticket for that.
> DOC-4437 - fixing broken link

- content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/deploy-corda-cluster.md
- content/en/platform/corda/5.0-beta/deploying/deployment-tutorials/manual.md
Describes the ability to specify a Kafka user for bootstrap and per type of worker. As part of this, the Corda CLI has been updated to accept a mapping of users to workers.
> DOC-4444 Support for multiple Kafka users

- themes/doks/layouts/partials/header/header.html
Banner updated from DP2 announcement to C4.5-C4.6 archiving announcement.
> banner-change

- content/en/platform/corda/4.5/enterprise/node/deploy/generating-a-node.md
- content/en/platform/corda/4.5/enterprise/operations/deployment/generating-a-node.md
- content/en/platform/corda/4.6/enterprise/node/deploy/generating-a-node.md
- content/en/platform/corda/4.6/enterprise/operations/deployment/generating-a-node.md
- content/en/platform/corda/4.7/open-source/generating-a-node.md
- content/en/platform/corda/4.8/enterprise/node/deploy/generating-a-node-cordform.md
- content/en/platform/corda/4.8/enterprise/operations/deployment/generating-a-node-cordform.md
- content/en/platform/corda/4.9/enterprise/node/deploy/generating-a-node-cordform.md
- content/en/platform/corda/4.9/enterprise/operations/deployment/generating-a-node-cordform.md
- content/en/platform/corda/4.9/enterprise/operations/deployment/generating-a-node.md
There are links of the form:
see [extended node configuration](../setup/corda-configuration-file.md). For
and:
see [extended node configuration](#generating-a-node-extended-config).
and
see [extended node configuration](#optional-configuration). 
Only the first appears legit. The second one goes to a non-existent heading. The third is self-referential, going to the heading of the section in which the link appears. So converting all such links to the first version.
> Doc 4490 - "extended node configuration" links now renamed and point to corda-configuration-file.md

- content/en/release-notes/_index.md
- content/en/release-notes/eol.md
1. The EoL paras on Corda index page was updated to read better and link through to main EoL page.
2. The EoL page was updated, with the main focus on a new table of links through to each archived version. Better and more obvious signposting was requested by dev evangelists - hence the table.
> end-of-life-signposts

- content/en/platform/corda/4.10/community/api-service-classes.md
- content/en/platform/corda/4.10/enterprise/cordapps/api-service-classes.md
ENT-7001 - added new section 'Service Lifecycle Events' to `API: Service Classes` (Community) and  'Using services in a flow' (Enterprise)
New section:
A Corda node will notify services when significant events occur via *service lifecycle events*. Upon initialization, a service can register a function to receive the events and act in whatever way is required. Handler functions do not need to handle every single type of event, merely the events that the service is interested in.
The Corda node issues events to all registered handler functions. Where multiple event handlers are registered, there is no guarantee for the order in which an event is dispatched to them.
The following service lifecycle events are issued by the node.
* **ServiceLifecycleEvent.BEFORE_STATE_MACHINE_START:** The node …
> ENT-7001 - added new section 'Service Lifecycle Events' to `API: Service Classes` (Community) and  'Using services in a flow' (Enterprise)

- content/en/platform/corda/4.10/community/release-notes.md
- content/en/platform/corda/4.10/enterprise/release-notes-enterprise.md
DOC-4524 - updated Enterprise and Community release notes with dependency info from Chris C (email 10 Jan)
Additionally, removed a release note entry accidentally added too early - https://r3-cev.atlassian.net/browse/ENT-8831. This actually belongs to 4.10.1, a later patch release.
> DOC-4524 - updated Enterprise and Community release notes with dependency info from Chris C (email 10 Jan)

- content/en/platform/corda/4.10/community/release-notes.md
- content/en/platform/corda/4.10/enterprise/release-notes-enterprise.md
ENT-8817 - Non-reentrant ConcurrentHashMap.compute() causes deadlock - added release notes entry:
"A rare condition was found when database transactions are rolled back under heavy load that caused flow state machine threads to stop processing flows, leading to eventual node lockup in certain circumstances.  This fix prevents this from happening."
> ENT-8817 - Non-reentrant ConcurrentHashMap.compute() causes deadlock - added release notes entry

- content/en/platform/corda/4.10/community/release-notes.md
- content/en/platform/corda/4.10/enterprise/release-notes-enterprise.md
ENT-8814: Transaction cache has memory leak
* Previously, a memory leak in the transaction cache occurred due to weight of in-flight entries being undervalued. Improvements have been made to prevent in-flight entry weights from being undervalued and, because they are now estimated more correctly, this results in a large decrease in the total size of cached entities.
(text from 4.9.5)
ENT-8811: Flow draining mode is broken and can acknowledge all the P2P messages in Artemis
* Flow draining mode no longer acknowledges P2P in-flight messages that have not yet been committed to the database. Previously, flow draining mode acknowledged all in-flight messages as duplicate.
(text from 4.9.4)
ENT-8796: Delay closing of attachment class loaders until all SerializationContext that refer to them …
> Add ENT-8814,  ENT-8811 and ENT-8796 to release notes

- content/en/platform/_index.md
- content/en/platform/corda/4.10/enterprise/_index.md
- content/en/platform/corda/_index.md
DOC-4532 - updated pages to show 4.10 links. Also fix to menu to put Enterprise 4.10 in right order
> DOC-4532 - updated pages to show 4.10 links. Also fix to menu to put Enterprise 4.10 in right order

- content/en/platform/corda/4.10/enterprise/node/setup/corda-configuration-fields.md
- content/en/platform/corda/4.10/enterprise/operations/deployment/corda-configuration-fields.md
Updated cryptoServiceFlowRetryCount - "....in the event of a flow suffering a CryptoServiceException due to a timeout.”
Also added description to same file under operations/deploy.
> DOC-4541 - updated cryptoServiceFlowRetryCount description and added to file under operations/deploy

- content/en/api-ref/_index.md
- content/en/api-ref/api-ref-corda-4.md
- themes/doks/layouts/index.html
- the root page the “Corda 4” box-out links are now for 4.10
- the [API ref page](https://paul.preview.docs.r3.com/en/api-ref.html) says now only includes Community 10 and Enterprise 4.5 to 4.10
- The [Corda 4 API ref page](https://paul.preview.docs.r3.com/en/api-ref/api-ref-corda-4.html) now has 4.10 links
> Doc 4543 - Update pages for 4.10

- content/en/platform/corda/5.0-beta/_index.md
Small change to make the REST API ref link on the homepage open in a new tab/window as this page is outside the main doc portal navigation.
> open REST API in new tab

- config/_default/menus/menus.en.toml
1. Delete traces of 4.9 Community from menu.toml.
2. Update homepage menu links to point to 4.10 and not 4.8 (Community & Enterprise)
> menu.toml update

- Dockerfile
- makefile
* adjusted installation procedure of s3deploy to the new name convention used by their developers
* s3deploy version updated to 2.9.0
* increase significantly upper limit of files to delete, otherwise a lot of them stays behind when a major reshuffle happens
> NOTICK: upgrade s3deploy to the newest version 2.9.0

- content/en/platform/corda/4.10/_index.md
- content/en/platform/corda/4.7/_index.md
- content/en/platform/corda/4.8/_index.md
- content/en/platform/corda/4.9/_index.md
"These pages aren't accessible from the menu (as far as I can see) and now in most cases simply link to the Enterprise version. Deleting the would avoid some breaking links down the line too (every time a Community edition is deprecated)."
> DOC-4730 - deleted unmenued index pages

- config.toml
update Algolia API key to match that specified on https://www.algolia.com/account/api-keys/all?applicationId=UX2KMUWFAL as described here: https://support.algolia.com/hc/en-us/articles/11217017604497-Why-am-I-getting-403-error-message-Invalid-Application-ID-or-API-key-status-403-with-DocSearch-
> update Algolia API key

- themes/doks/assets/scss/layouts/_header.scss
- themes/doks/assets/scss/layouts/_home.scss
Jira: https://r3-cev.atlassian.net/jira/software/c/projects/FE/boards/867?modal=detail&selectedIssue=FE-52 
Changed the opacity of the background image of navbar of the site header to 1. So that scrolled text can not be seen.
See screenshot:
> FE-52: Update nav bar so that scrolled text can not be seen

- content/en/platform/corda/1.5/cenm/_index.md
- content/en/platform/corda/4.10/enterprise/flow-state-machines.md
- content/en/platform/corda/4.10/enterprise/operations/deployment/firewall-deployment.md
- content/en/platform/corda/4.7/enterprise/flow-state-machines.md
- content/en/platform/corda/4.7/enterprise/operations/deployment/firewall-deployment.md
- content/en/platform/corda/4.8/enterprise/flow-state-machines.md
- content/en/platform/corda/4.8/enterprise/operations/deployment/firewall-deployment.md
- content/en/platform/corda/4.9/enterprise/flow-state-machines.md
- content/en/platform/corda/4.9/enterprise/operations/deployment/firewall-deployment.md
1. 8 fixes applied as per Algolia crawler results for 404s.
2. The links with anchors have moved from absolute links to .md in the recommended relref format. 
Use of the highly recommended (by Hugo) refs and relrefs is not worse than having them in absolute form and may offer benefits longer term. They still don't work with index files, but that is a unique and separate issue. There is also scope to potentially bulk change in one swoop, all absolute links to the new format, but that is for another day. This is just to prove that these are stable in all stages of build (including live) and to see if their use causes 404s to stop for those entries.
> 8-original-link-fixes

- themes/doks/layouts/sitemap.xml
Hugo generates a sitemap, but it only contains relative URLs, which Google can't consume. This task is to update the sitemap template to prefix it with [docs.r3.com](http://docs.r3.com/) so that the sitemap URLs are absolute. Google can then consume this sitemap and (hopefully) it means that new and deleted pages are updated in their index automatically and more quickly.
> DOC-4864 - Configure sitemap to be consumable by Google

- content/en/platform/corda/5.0-beta/_index.md
- themes/doks/layouts/partials/head/head.html
Currently the meta descriptions for all pages in Hugo comes from the setting title = "R3 Documentation" in the config.toml. This is probably why Google then tried to invent its own meta descriptions for our pages, so for example for Corda 5 Beta 1 it’s as shown below.
This ticket is to update the head.html to add a meta description tag which allows you to specify a “description” tag in a page’s front matter. So for example:
`description: "Testing meta data"
title: Corda 5.0 Beta 1`
Will render as:
`<title>Corda 5.0 Beta 1 - R3 Documentation</title><meta name=description content="Testing meta data">`
> Testing meta data

- content/en/platform/corda/4.10/community/legal-info.md
- content/en/platform/corda/4.10/community/release-checksum-os.md
- content/en/platform/corda/4.10/community/release-notes.md
- content/en/platform/corda/4.10/community/release-platform-support-matrix.md
**Jira**: https://r3-cev.atlassian.net/browse/FE-67
The collapse/expand icon (point right when collapsed, and point down when expand) on the lefthand menu does not work for Corda Community 4.10 page. Works fine on all others.
the identifier value for `release-notes` set to `"4-10-release-notes"`, then it was used to dynamically setup `data-bs-target` & `aria-controls` attributes for the collapse/expand button. But CSS/html rules string start with number does not works with querySelector, hence the error here. Then it causes the collapse/expand icons not working for the whole page.
Change the identifier and related fields to `"corda-community-4-10-release-notes"` will solve the bug.
> FE-67: Lefthand menu collapse/expand icon not working for Corda community 4.10

- themes/doks/layouts/partials/header/header.html
Quick PR to delete unintentional space added by VS code auto formatting for html file.
> FE-68: deleted unintentional space added by vs code that causing logo bug.

- content/en/platform/corda/_index.md
1. Table changed so that no more link text just saying 'link' or 'archive link'. 
2. To keep it in table format, I changed the left hand column to product, which I think works well, given that the archive list in particular is quite long, without further breakdown.
3. Fixed some naming convention issues; e.g. _Corda 4.3 Enterprise_ vs _Corda Enterprise 4.3_
4. Changed the 4.10 product name, after a lot of back and forth with product, which will affect how we manage Community and OS, which are two separate things that are both still current. (I will brief you all at next SU)
> change table format&consistency in name convention

- content/en/platform/corda/_index.md
- content/en/platform/corda/archived-versions.md
- content/en/platform/corda/eol-schedule.md
1. Move EOL content out to dedicated no-index page, as per Elfreda request.
2. Move archived list out to separate no-index page.
3. Just have Corda _index page for current supported docs list and add links to two above sections  moved to their own pages.
> move-eol-and-archive-list

- themes/doks/assets/scss/components/_tables.scss
1. Header row more distinct (not white, as it is now), plus border top and bottom added to help define.
2. Cancel the alternate rows being grey and white, which is nasty looking.
3. Finally added fine grey borders.
Preview to follow shortly
> css-changes-to-tables

- content/en/platform/corda/4.10/enterprise/cordapps/token-sdk-introduction.md
- content/en/platform/corda/4.7/enterprise/cordapps/token-sdk-introduction.md
- content/en/platform/corda/4.8/enterprise/cordapps/token-sdk-introduction.md
- content/en/platform/corda/4.9/enterprise/cordapps/token-sdk-introduction.md
Removed Tokens SDK release notes and added a link to the release notes in each Corda version.
> Removed Tokens SDK release notes from each Corda version

- themes/doks/assets/scss/common/_global.scss
JIRA: https://r3-cev.atlassian.net/browse/FE-73
Breadcrumb is now fixed at the top of pages so that it’s always visible, regardless of user scrolling.
However, the original position/layout is kept for smaller screen (e.g. on mobile deviceS), meaning it will get hidden once user scroll further down the page. Since we got very limited display on small device, it's best practice and common to not to fix non-essential ui element on the screen.
> FE-73: Fix breadcrumb's position 

- themes/doks/assets/js/app.js
- themes/doks/assets/scss/common/_global.scss
Bug spotted by @nadinequinr3 
It's caused by previous PR on fixing the position of breadcrumb on the page:
If you follow a link to a specific heading for example from right-hand table of content, the heading is hidden by the breadcrumb.
> FE-73: Fixed the bug caused by fixing breadcrumb position

- themes/doks/layouts/shortcodes/figure.html
The "new" structure of the C5 content uses [Hugo page bundles](https://gohugo.io/content-management/page-bundles/). Currently, the `figure` shortcode used to display images does not process images saved as part of a page bundle.
> Update figure shortcode to check for page resource

- themes/doks/assets/scss/common/_dark.scss
JIRA: https://r3-cev.atlassian.net/browse/FE-85
When we fixed the position of the breadcrumb, the background color has to be set so that the content below scrolls through can be hidden.  But when the site is in dark mode, the background color needs to change to match the dark theme. See the screenshot for the bug:
So I added the styling for the dark theme background.
Screenshot of the breadcrumb after the fix:
> FE-85: Breacrumb background bug when on dark mode.

- themes/doks/assets/scss/common/_global.scss
- themes/doks/layouts/_default/_markup/render-heading.html
"It would be more intuitive to also have the little ‘link' icon can display beside each heading to make that more intuitive. Probably light grey (so as not in the reader’s face) to the right of each heading. This means that when the reader clicks the link beside a header, the URL at the top changes from [www.xyz.com](http://www.xyz.com/) to [www.xyz.com#headinglink](http://www.xyz.com/#headinglink). That enables customer support and users to send links directly to relevant content, which is helpful as some of our pages are rather large. Probably only relevant for H2"
JIRA: https://r3-cev.atlassian.net/browse/FE-71
Based on the ticket requirement. All headings from `H2` downward have been changed to link heading, with the 🔗 unicode icon at the end only visible when on hovering. …
> FE-71: Add link heading with icon on hover at the end.

- themes/doks/assets/scss/common/_global.scss
- themes/doks/layouts/_default/_markup/render-heading.html
The implementation in [FE-71: Add link heading with icon on hover at the end. (#1288) · corda/corda-docs-portal@2bee5b2](https://github.com/corda/corda-docs-portal/commit/2bee5b27ed3626670fc894c0a9e23a0c16fc4940) has caused several issues:
- Double H1s on some pages
- icon in search results
- icon in previews of pages
> Rollback Heading Link Changes

- themes/doks/assets/scss/common/_dark.scss
JIRA: https://r3-cev.atlassian.net/browse/FE-86
Table background not suitable when on dark mode, see screenshot below:
Changed the table background-color styling to match the main content background. See screenshot after the fix:
> FE-86: Fix table row background issue on dark mode.

- content/en/platform/corda/5.0/reference/config-fields/_index.md
The ticket relates to the `corda.sandbox` config but those changes are picked up automatically from GitHub. This PR is just to address some small tweaks to the sample command.
> tidy up sample config commands

- config.toml
- Swapped algolia api key to appadmin 'Search' key, with less permissions than existing 'Search' key.
> change-algolia-api-key

- content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
references of annotation-key-2/is-safe changed to annotation-key-2: "some-value"
>  Niamh25/DOC-5173/Corda-deployment-fix

- content/en/platform/corda/5.0/application-networks/tooling/installing-corda-cli.md
- content/en/platform/corda/5.0/deploying-operating/deployment/deploying/_index.md
- content/en/platform/corda/5.0/deploying-operating/tooling/installing-corda-cli.md
- content/en/platform/corda/5.0/developing-applications/tooling/installing-corda-cli.md
Customer Hub will now only host Corda Enterprise files.
As per @milan-khan "we should say:
for enterprise customers download from CHUB
for non-enterprise customers download from the Developer Portal"
> update Beta 4 download locations

- themes/doks/layouts/shortcodes/figure.html
The change to the Figure shortcode to check for image files in a resource bundle did not take into account the structure in the CDL content
> update shortocde for cdl images directory structure

- themes/doks/assets/scss/common/_global.scss
- themes/doks/layouts/partials/sidebar/pages_in_version_menu.html
JIRA: https://r3-cev.atlassian.net/browse/FE-91
The simple fix would be to add a tooltip to the truncated context of the sidebar menu.
The option to make the sidebar resizeable can be tricky due to how the base layout of the doc site setup. Also by doing that, we might need to fix any potential bugs introduced by the resizeable sidebar to other UI elements.
Overall tooltip for now is a better fix at the moment.
> FE-91: Added tooltip to sidebar link content.

- themes/doks/layouts/partials/sidebar/pages_in_version_menu.html
Previous PR (https://github.com/corda/corda-docs-portal/pull/1491) only add a tooltip to the menu without children.
As Nadine suggested, it would be helpful to add a tooltip to all menu items, even the ones with a sub-menu.
> FE-91: Added tooltip for menu with sub-pages.

- content/en/tools/ledgergraph/ledgergraph-index.md
1. Multiple regex expressions tested to try to identify links missed. 
2. All .md links (./ and ../) are now changed to new format (with or without # tag).
3. Only one link error spotted that had been previously formatted wrongly. This is now fixed.
Only relative links ending in .html (with and without tags) to be changed now.
> single link format fix

- themes/doks/layouts/shortcodes/tooltip.html
Glossary tooltips weren't centered correctly above the term. This also had the effect of some tooltips displaying off-screen.
> Center Glossary Tooltips

- themes/doks/layouts/shortcodes/figure.html
The error message when an image file is not found for the `figure` shortcode was badly formatted and did not include the position of the error.
Before:
After:
> Update figure error message

- themes/doks/layouts/shortcodes/glossary.html
- themes/doks/layouts/shortcodes/tooltip.html
- Add an arrow to glossary tooltips
- Add an HTML `id` to the terms in the full glossary list so we can link to them.
Preview here: https://nadine.preview.docs.r3.com/en/platform/corda/5.0.html
> Add hyperlinks to glossary terms

- themes/doks/layouts/shortcodes/tooltip.html
.. to the item in the full glossary, which has more info.
Preview here: https://nadine.preview.docs.r3.com/en/platform/corda/5.0.html
> Add hyperlinks from glossary tooltips to the item in the full glossary, with more info

- content/en/platform/corda/5.0/reference/corda-cli/database.md
- content/en/platform/corda/5.0/reference/corda-cli/initial-config.md
- content/en/platform/corda/5.0/reference/corda-cli/mgm.md
- content/en/platform/corda/5.0/reference/corda-cli/package.md
- content/en/platform/corda/5.0/reference/corda-cli/secret-config.md
- content/en/platform/corda/5.0/reference/corda-cli/topic.md
All tables in the CLI reference sections have the same column width to make them uniformed.
> Niamh25/doc 5700/cli ref table widths

- themes/doks/config/_default/params.toml
- themes/doks/layouts/_default/_markup/render-heading.html
- themes/doks/layouts/_default/list.html
- themes/doks/layouts/_default/single.html
There are several differences in the way Corda 5 content is rendered. For example, H1s don't come from the front matter and there is no right-hand menu.
This PR creates a new site parameter to contain a list of the Corda 5 doc versions. This variable is now checked when determining how to render content. As a result, when there is a new Corda 5 version, this now only needs to be added to the site parameter and not in multiple places.
Preview here: https://nadine.preview.docs.r3.com/en/platform/corda/5.0.html
> Add new site param for Corda 5 versions

- content/en/platform/corda/5.0/application-networks/creating/members/virtual-node.md
- content/en/platform/corda/5.0/application-networks/creating/mgm/virtual-node.md
The request to create a virtual node no longer "returns the details of the new virtual node as JSON", but rather a requestId which can be used in GET /api/v1/virtualnode/status/{requestId} to get an update.
This was not reflected in the MGM section.
> Update the response from MGM virtual node creation

- themes/doks/layouts/partials/head/seo.html
For example:
After:
Preview here: https://nadine.preview.docs.r3.com/
> Title of version landing pages displays the version twice

- content/en/platform/corda/5.0/reference/rest-api/accessing.md
Small fix after David Currie comment on corda-docs Slack channel.
The secret reference was old and needed to be updated to the new reference.
> changed-secret-reference

- content/en/platform/corda/5.0/_index.md
- themes/doks/layouts/partials/main/docs-navigation.html
Preview here: https://corda5.preview.docs.r3.com/
> The "Next" navigation was not displayed on the footer of version landing pages

- themes/doks/assets/scss/common/_global.scss
- themes/doks/layouts/index.html
Preview: https://paul.preview.docs.r3.com/
Our landing page cards are clickable, yet the click doesn't lead anywhere. Instead, the links are buttons within the card <p> element. This is not very intuitive. As part of a larger set of potential changes to landing page:
1. Cards with one link are now entirely clickable.
2. The C5 card title was **Corda 5.0**, whereas the C4 card was **Corda 4**. The C5 card is now **Corda 5**.
3. The two highlighted cards (red) are not external links any more. The external symbol is removed accordingly.
4. The highlighted card (blue) is still external, but there was a problem adding the external symbol AND making the entire card clickable. For now, I have run with making the entire clickable and I have a question in with FE team around adding the external …
> making landing page cards clickable

- themes/doks/assets/scss/layouts/_footer.scss
- themes/doks/layouts/partials/footer/footer.html
There will be lots of changes to footer, header, and landing page of docs over next week or so. These changes are best achieved in iterative approach. There are lots of other things still to change even for this footer, so this is not the final state.
1. Remove Docs link from footer.
2. Remove two other links from right side of footer.
3. Tweak footer style to close up the columns.
> delete Docs link & other footer links

- content/en/platform/corda/5.1/deploying-operating/config/fields/crypto.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/db.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/externalMessaging.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/flow.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/ledger-utxo.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/membership.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/messaging.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/p2p-LinkManager.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/p2p-gateway.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/reconciliation.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/rest.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/sandbox.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/secrets.md
- content/en/platform/corda/5.1/deploying-operating/config/fields/security.md
- content/en/platform/corda/5.1/reference/rest-api/openapi.html
Preview: https://corda5.preview.docs.r3.com/en/platform/corda/5.1.html
> Update GitHub source paths to 5.1 versions

- content/en/platform/corda/5.1/developing-applications/packaging/code-signing/custom-cert.md
Preview here: https://corda5.preview.docs.r3.com/en/platform/corda/5.1/developing-applications/packaging/code-signing/custom-cert.html
> Make API Cert name singular

- layouts/partials/defs-field-desc-ref-docs.html
- layouts/partials/field-desc-ref-docs.html
- layouts/partials/referenced-field-desc-ref-docs.html
.. Previously, 0 values were not rendered in the docs.
For example:
Before:
After: (https://nadine.preview.docs.r3.com/en/platform/corda/5.0/deploying-operating/config/fields/messaging.html)
> Update how the shortcodes check if a config value is defined..

- themes/doks/layouts/shortcodes/tooltip.html
> Update glossary tooltip to default to latest version (5.1)

- content/en/platform/corda/5.1/deploying-operating/observability/metrics/ledger.md
Metrics are sorted alphabetically now. Moved UTXO Ledger to the end of the metrics list.
> DOC-6024: Moved UTXO Ledger to the end of the metrics list

- themes/doks/layouts/shortcodes/tooltip.html
Fix for hyperlinks on plural versions of glossary terms. For example, the glossary items in this section: https://docs.r3.com/en/platform/corda/5.0/key-concepts/cluster-admin/workers.html#workers
Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.0/key-concepts/cluster-admin/workers.html#workers
> Update how hyperlinks for glossary terms are generated

- hugo.toml
- themes/doks/config/_default/config.toml
Hugo can use git variables to give an accurate date modified for each page. 
Preview: https://neil.preview.docs.r3.com/
For example:
Page source for https://docs.r3.com/en/platform/corda/5.0.html:
Page source for https://neil.preview.docs.r3.com/en/platform/corda/5.0.html:
> Enable git variables

- themes/doks/assets/scss/common/_global.scss
Before:
After:
Before:
After:
Preview: https://colin.preview.docs.r3.com/ **To be reviewed by all team members to ensure that the change is as expected on all pages.**
> Correct margin for paragraphs inside lists

- content/en/platform/corda/5.1/deploying-operating/observability/metrics/_index.md
Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/observability/metrics.html
> Filter Corda Metrics in Prometheus through the Pod Monitor

- layouts/partials/field-desc-ref-docs.html
Before:
Preview: https://nadine.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/config/fields/p2p-gateway.html
> Update JSON config shortcode to use different formatting when default value is for a set of values

- hugo.toml
- themes/doks/layouts/partials/head/opengraph.html
Configure Hugo to set `article:published_time` to the last modified date from Git and include this in the `<head>` of section and child pages.
> article:published_time

- config/_default/params.toml
- themes/doks/layouts/partials/head/opengraph.html
- themes/doks/layouts/partials/head/twitter_cards.html
- Removed summary from Open Graph descriptions. This is often badly formatted and not fit for purpose.
- Also, updated the Twitter account.
> Remove summary from Open Graph description

- config/_default/params.toml
- themes/doks/layouts/index.html
- themes/doks/layouts/shortcodes/tooltip.html
The Corda 5 Key Concepts link on the homepage was still pointing to 5.0. Updated the code to always use the newest version.
> Code homepage links to point to latest C5 version

- themes/doks/assets/scss/common/_global.scss
The space between code blocks was too great. When this was reduced, lists looked too squashed so consistently increased all spacing within list items.
**Example 1**
Before:
After:
Preview: 
https://neil.preview.docs.r3.com/en/platform/corda/5.1/application-networks/creating/mgm/cpi.html
**Example 2**
Before:
After:
Preview: 
https://neil.preview.docs.r3.com/en/platform/corda/5.1/deploying-operating/deployment/deploying.html#container-images-for-corda
> Make spacing around code blocks inside lists consistent with other content

- themes/doks/assets/scss/components/_code.scss
- Copy button now only displays on hover. This button was hiding code text previously.
- Scrollbar for long lines of code is now always displayed. Previously, this was only displayed on hover meaning users might not realise there was more code not displayed.
Preview: https://colin.preview.docs.r3.com/
> Code Block Improvements

- config/_default/params.toml
- themes/doks/layouts/404.html
- themes/doks/layouts/partials/footer/footer.html
Pushed footer to bottom of 404 page. Preview from local build:
Also fixed https://r3-cev.atlassian.net/browse/DOC-6334. Updated copyright year to variable so that it is always correct.
Preview: https://amie.preview.docs.r3.com/
> Update copyright year and fix footer on 404

- Dockerfile
* Node.js v14 is not longer supported and an upgrade to the current version (20) is recommended by the project
* also update `npm` to recommended major version (10.4.0)
> ES-1938: update Node.js from v14 to v20

- themes/doks/assets/scss/components/_tables.scss
Reduced the space below tables (it was greater than the space above headings).
Some examples:
1. 
2.
3.
> Reduce white space below tables

- content/en/platform/corda/5.1/developing-applications/notaries/_index.md
Preview: https://colin.preview.docs.r3.com/en/platform/corda/5.1/developing-applications/notaries.html#application-cpb
> Remove confusing reference to runtime-os

- content/en/api-ref/_index.md
- content/en/api-ref/api-ref-corda-4.md
Updates to API index page. Left-hand menu and headings are confusing.
Preview: https://amie.preview.docs.r3.com/en/api-ref.html
> API References Index Page

- content/en/platform/corda/5.2/deploying-operating/deployment/upgrading/_index.md
Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.2/deploying-operating/deployment/upgrading.html#upload-the-corda-cpis-to-virtual-nodes
> DOC-6460: Added an extra step to 5.1 to 5.2 upgrade instructions

- content/en/platform/corda/5.2/developing-applications/cordapp-template/prerequisites/_index.md
Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.2/developing-applications/cordapp-template/prerequisites.html#software-prerequisites
> DOC-6477: Added installing Corda CLI link to CorDapp template prereqs

- content/en/platform/corda/5.3/deploying-operating/deployment/deploying/_index.md
Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.3/deploying-operating/deployment/deploying.html#using-hashicorp-vault-in-the-openshift-environment
> DOC-6451: Updated the External Secrets Service section of the Corda 5.3 deployment instructions

- content/en/platform/corda/5.2/deploying-operating/deployment/deploying/_index.md
Preview: https://anna.preview.docs.r3.com/en/platform/corda/5.2/deploying-operating/deployment/deploying.html#external-secrets-service
> DOC-6568: Required vault token capabilities

- themes/doks/layouts/partials/footer/script-footer.html
Verified jQuery is now on a newer version when inspecting the preview site.
Chrome DevTools console output:
```
> jQuery.fn.jquery
'3.7.1'
```
> ES-2709: bump Jquery version to 3.7.1
